### ISSUE TITLE
Few questions about lock

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/helpdesk#1]
1. ticketlock이 spinlock과 peterson's mutex의 기능을 합쳐 놓은 느낌인가요?
2. ppt 63page에 "All SC fences are strictly ordered w.r.t the per-thread views"라는 문장의 의미를 자세히 설명해 주세요.
3. ppt 71page에 있는 ticket lock과 MCS parking lock에 대해 다시 한 번 설명해 주실 수 있을까요?
---------------------------in english---------------------------------------
1. Does ticketlock feel like a combination of spinlock and peterson's mutex?
2. Please explain in detail the meaning of the sentence "All SC fences are strictly ordered w.r.t the per-thread views" on page 63 of ppt.
3. Could you explain again about the ticket lock and MCS parking lock on page 71 of ppt?

Thankyou :)

**Comment by jeehoonkang** [comment]
1/4. No.  Ticket lock is also spinning on a location, but it guarantees fairness by designating a location for critical section orders.

2/5. There exists a linear order among all the SC fences in an execution; and the per-thread view at the time that an earlier SC fence is executed, is incorporated to the per-thread view at the time that a later SC fence is executed.

3/6. CLH/MCS lock is different from ticket lock in that in CLH/MCS lock, each critical section is spinning on its own location different from those of each other.  MCS parking lock is different from MCS lock in that a thread is parking (i.e. sleeping) if it's not it's turn to enter the critical section.

**Comment by Shynar88** [comment]
Thank you for writing questions and answers in English!
