### ISSUE TITLE
What is the behavior of views in case of sequential rmw instructions?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#10]
Could you, please, explain, how do views behave with rmw instructions?
For example:
![Screen Shot 2019-10-13 at 19 25 24](https://user-images.githubusercontent.com/38908309/66714227-30034c80-edef-11e9-937f-d0be463b618c.png)
1) In order to avoid such situations, does this mean that if one of the threads wants to make rmw instruction on the variable, the thread should transfer its view to the latest rmw instruction's message(or just latest write message?) first, and only then perform rmw? 
2) What happens in the case if some another thread(say t5) wants to read value from the variable which had rmw instructions performed on it? Should t5 read the message with timestamp >= the timestamp of latest rmw instruction's message made by other thread, or t5 can read the message with timestamp >= the timestamp of t5 current view's message?

**Comment by jeehoonkang** [comment]
- Please write text as text, not image.
- In 2), even though t2's view was on the 0 message, it decided to read from the 1 message.  Recall the invariant that the written message should be adjacent to the read message for RMWs.
- I believe the above explanation clarifies the semantics and you can answer questions 1. and 2. yourself, but feel free to ask follow-up questions.

**Comment by Shynar88** [comment]
Thank you! I understood how to answer Q1. 
Did I understand the answer to Q2 correctly? 
For Q2, Another thread, making read instruction, can read any message which is >= thread's current view.

**Comment by jeehoonkang** [comment]
On Q2: yes, another thread may read from a message with timestamp >= it's current view, if it's executing a load instruction (not rmw).

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have followup questions.
