### ISSUE TITLE
Difference between two methods of getting WriteGuard?

### ISSUE THREAD

**Issue by kunduzb17** [kaist-cp/helpdesk#101]
As it was discussed previously for using atomic_write to inner value of the node we need to get a  `WriteGuard,` and  that we have to first use `read_lock()` and that make un `upgrade().` But why can't we just use `write_lock()` since it is also returns `WriteGuard`. Could you please explain differences ?

**Comment by jeehoonkang** [comment]
It should be the same.  If both are possible, upgrading from a read lock is supposed to be faster because it already has the sequence number.

**Comment by dnkim** [comment]
But if we use `write_lock` we cannot know that the node is still valid, can we?

**Comment by jeehoonkang** [comment]
Yes, and after newly acquiring a write guard, you need to recheck the node is still valid.

**Comment by dnkim** [comment]
Is it possible? I mean, acquiring write lock will increase sequence number of sequence lock and make read lock impossible to validate from my understanding.
