### ISSUE TITLE
Confused about "discard current node".

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#103]
1) From what I understood, pop() ```defer_destroy```s curosor's current. But then I am confused, to what should cursor.current point as the result of operation? To it's parent node? Or instead of ```defer_destroy``` should pop() just mark cursor's current node as vacant?
2) Do I understand the usage of existing API right: cleanup() is called in delete(); and pop() is a helper function of cleanup(), so pop() is not directly called by delete()?

**Comment by jeehoonkang** [comment]
1. `pop()` is not meant to be `defer_destroy()` anything.  It's traversing up, resulting to point to the parent.
2. AFAICT, yes.

**Comment by Shynar88** [comment]
If it is not pop()'s duty to call defer_destroy(), then is it done by cleanup()?

**Comment by jeehoonkang** [comment]
@Shynar88 Yes, I expect cleanup() to call defer_destroy() a node after detaching it.

Closing it, but feel free to reopen it.
