### ISSUE TITLE
Does not protecting reads in lookup with Write Guard invalidate the purpose of OLC?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#104]
https://github.com/kaist-cp/cs492-concur/issues/17#issuecomment-558465665

Does not protecting reads in lookup with Write Guard invalidate the purpose of Optimistic Lock Coupling? If I understood correctly, the motivation of OLC is that cache is not invalidated during reads. But if lookups(reads) are protected with WriteGuard(writes to the memory occur), doesn't this invalidate the purpose of OLC we are trying to implement in this HW?

**Comment by jeehoonkang** [comment]
Yes in part, no in part.  Yes, it's awkward to acquire a write lock in read.  But still, the number of (write-)locking reduces from the height to 1, which is a significant improvement for some workloads.

**Comment by Shynar88** [comment]
Why we protect reads by Write Guard only in lookup() function?

**Comment by jeehoonkang** [comment]
1. Because our `lookup()` function doesn't understand (or support) validation.  The only safe way to ensure a read is always valid (as mandated by the `lookup()` function's signature) is acquiring a write guard.

Closing it, but feel free to reopen it.
