### ISSUE TITLE
What if lookup doesn't find a key?

### ISSUE THREAD

**Issue by AnuarTB** [kaist-cp/helpdesk#107]
In the function comment it is said that the function f will be called on found `value`, however what should happen if key is not in the BST?

**Comment by planetarynebula** [comment]
Function `f` gets `Option<&V>` as an argument. So, it can get `None` as an argument. Return `f(None)`.

**Comment by jeehoonkang** [comment]
I agree with @planetarynebula .

Closing it, but feel free to reopen it.
