### ISSUE TITLE
About grading criteria

### ISSUE THREAD

**Issue by mjy0503** [kaist-cp/helpdesk#109]
`bst_stress_concurrent` test doesn't mean my code is correct.
By https://github.com/kaist-cp/helpdesk/issues/85, we will learn about correctness at Monday.
However, HW2 deadline is before the class.

For HW2, is there any method to test correctness?
Also, is there any time or memory limit?

**Comment by tomtomjhj** [comment]
This doesn't guarantee correctness but I'd recommend you to run tests with shorter keys for more contention:
```rust 
fn generate_random_string(rng: &mut ThreadRng) -> String {
    // let length = rng.gen::<usize>() % 128;
    let length = 1;
    rng.sample_iter(&Alphanumeric).take(length).collect()
}

```

**Comment by jeehoonkang** [comment]
@mjy0503 Monday, we "discussed" how to strictly test BST (11/25, not 12/02).

**Comment by jeehoonkang** [comment]
FYI, the deadline changed: https://github.com/kaist-cp/cs492-concur/issues/17#issuecomment-559354903

**Comment by mjy0503** [comment]
@jeehoonkang 
Is there specific time(memory) limit?

**Comment by jeehoonkang** [comment]
Nothing specific, but you should not spend too much time or memory...  Though I'll not be too harsh on time and memory.
