### ISSUE TITLE
Views in release/acquire 

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#11]
![Screen Shot 2019-10-13 at 20 03 30](https://user-images.githubusercontent.com/38908309/66714681-9a6abb80-edf4-11e9-9a67-3e222233dc75.png)

1) Does load(acquire) make it mandatory for the thread to load the message only with the per-message view annotated into it? In other words, in the example presented above, the dark green thread has to read Y=1 (it can't read Y=0), because Y=1 has per-message view annotated into it?
2) In case there are several threads executing store( , release), when executing one load(acquire) which of the store( , release) messages thread should read?

**Comment by jeehoonkang** [comment]
1. No.  If you're load-acquiring a message without an annotated view, then no view is incorporated to the current thread's view.  In particular, the right thread can read Y=0, without modifying it's per-thread view.

2. When a thread may read from arbitrary messages, as far as it's not before the thread's per-thread view.  Thus the semantics is nondeterministic: you have to consider executions in which a load reads from a mesasge, and executions in which a load reads from another message.

**Comment by Shynar88** [comment]
Thank you! #2 is clear. 
For clarification, in #1, in the scenario described in the answer(that right thread can read Y=0 in the picture provided), the Y.load(acquire) can result in Y=0? 
It's interesting, because before I thought that release-acquire synchronization forces Y.load(acquire) to result in Y=1 in all cases(in other words, forces the right thread to read 1 from Y, not 0).

**Comment by jeehoonkang** [comment]
Regarding Q1: yes, T2 can read Y=0.  Release/acquire on X does not enforce a thread to read a particular message of X.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have followup questions.
