### ISSUE TITLE
Correctness of concurrent data structures

### ISSUE THREAD

**Issue by hieudz** [kaist-cp/helpdesk#110]
Hi,

How do we know the design of a data structure for multi-threads is correct? In other words, what is the definition of correctness for a concurrent data structure? The definition I have in mind now is that the multi-threaded version should produce the same result as the single-threaded one.

In the paper, the data structure defined some functions, namely get, put, remove, etc. But it seems like if we run the AVL in parallel (or in concurrence), those functions will generate a different output compared to the output of single-threaded implementation.

For example, let's consider the following sequences:
put(3)
get(3) 
it may either return null or 3 in concurrent implementation, but it will definitely return 3 in the single-threaded implementation. In this case, is the design incorrect?

Many thanks.

**Comment by tomtomjhj** [comment]
As mentioned in the paper, _linearizability_ is one of the correctness criteria. Since I haven't looked deeply into this concept, I'd recommend you to take a look at chapter 3 of _Art of Multiprocessor Programming 2nd_ by Shavit et al.

**Comment by jeehoonkang** [comment]
@hieudz @tomtomjhj Some people think "contextual refinement" is the right specification.  It can be proved from linearizability, though.
