### ISSUE TITLE
Implementing lookup() with WriteGuard

### ISSUE THREAD

**Issue by choi7023546** [kaist-cp/helpdesk#111]
From this comment, Do you mean upgrade cursor.guard (now this is ReadGuard) to WriteGuard before traversing for that node?
----------------------------------------------------------
- How to protect the tree's value in ConcurrentMap::lookup()?
Please protect the reads with WriteGuard, not ReadGuard. Yes it's ugly, but let's just strongly protect value reads...
-----------------------------------------------------------

**Comment by jeehoonkang** [comment]
I meant to write-protect the node containing the value you're looking up.

**Comment by jeehoonkang** [comment]
Closing it, but feel free to reopen it if you have follow-up questions!
