### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by bprovot** [kaist-cp/helpdesk#116]
I can't figure out my upgrade error `self.guard.deref().upgrade();
move occurs because value has type lock::seqlock::ReadGuard<'_, bst::base::NodeInner<K, V>>, which does not implement the Copy trait`. 

Did somebody have the same issue ?

**Comment by bprovot** [comment]
Ok I figured calling `upgrade() ` on a `deref()` was not a good idea so I'm trying with ìnto_inner()`but now I have another error which is the use of a moved value, and I don't really see how to get through that.

**Comment by jeehoonkang** [comment]
how about `self.guard.clone().upgrade()`?

**Comment by bprovot** [comment]
Clone doesn't solve the problem, now it says that  `cannot move out of dereference of std::mem::ManuallyDrop<lock::seqlock::ReadGuard<'_, bst::base::NodeInner<K, V>>>` when calling it on self.guard.clone().upgrade()

**Comment by jeehoonkang** [comment]
how about `ManuallyDrop::into_inner(self.guard.clone()).upgrade()`?

**Comment by bprovot** [comment]
Yes that seems to work ! That was actually a merge of both of the solutions tried. I think I understand why now ! Thank you !

**Comment by bprovot** [comment]
However, the upgraded guard is a WriteGuard made from a clone of the initial readguard. Is that sufficient to aquire properly the guard ?

**Comment by jeehoonkang** [comment]
Yes, it's sufficient because the sequence number is copied.

**Comment by zoonoo** [comment]
I modified my implementation after reading this issue, but I'm unable to use `clone()` method on my `ReadGuard`.

I've tried a few things based on the help from the compiler but was unsuccessful.
How can I make `ManuallyDrop<>` implement `Clone`?

```
    |
227 |         while ManuallyDrop::into_inner(cursor.guard.clone()).upgrade().is_err() {}
    |                                                     ^^^^^ method not found in `std::mem::ManuallyDrop<lock::seqlock::ReadGuard<'_, bst::base::NodeInner<K, V>>>`
    |
    = note: the method `clone` exists but the following trait bounds were not satisfied:
            `std::mem::ManuallyDrop<lock::seqlock::ReadGuard<'_, bst::base::NodeInner<K, V>>> : std::clone::Clone`
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the method `clone` exists but the following trait bounds were not satisfied:
            `std::mem::ManuallyDrop<lock::seqlock::ReadGuard<'_, bst::base::NodeInner<K, V>>> : std::clone::Clone`
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following trait defines an item `clone`, perhaps you need to implement it:
            candidate #1: `std::clone::Clone`
```

**Comment by jeehoonkang** [comment]
would you please try `cargo update`?

**Comment by zoonoo** [comment]
Ah... Thank you!
