### ISSUE TITLE
Bst Sequential Test problem

### ISSUE THREAD

**Issue by bprovot** [kaist-cp/helpdesk#117]
I tried to do the tests for HW2 but I am locked in an infinite loop in my find function although the smoke test works. Do you have any idea to what that could be linked ?

**Comment by bprovot** [comment]
I think I found my issue, but could I have the confirmation that bst_stress test checks that the reordering is done ? I think my problem is here

**Comment by Shynar88** [comment]
I am not sure what you mean under the word "reordering". As I understood, bst_stress() uses one thread for testing, thus the tree should behave like a hash map(the similar way the ART was tested). And bst_stress_concurrent() uses several threads.

**Comment by bprovot** [comment]
yeah no I was able to find what the error was, this is not what it thought I'm gonna close this stopic and open another one
