### ISSUE TITLE
 Cursor::find()'s behavior depending on the result of Cursor::push()

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#120]
In the Cursor::find() function, the comment says: 
"Cursor::push() ...... If unsuccessful, retry from the beginning."

I currently match the output of Cursor::push() with Ok() and Err() case. However, it seems that in both cases the actions are the same - do nothing, just let it go to the beginning of the loop in find() function. Because in case of Ok() we just continue traversal, in case of Err() the push() didn't change the cursor's current, so starting the loop from the beginning seems enough. Am I confusing something, just according to the comment, it seems that Err and Ok cases should be handled differently?

**Comment by jeehoonkang** [comment]
I assumed `Cursor::push()` iteratively traverses down the tree.  "retry from the beginning" is meant to be starting again from the root.

**Comment by temirrr** [comment]
@jeehoonkang oh, I thought that we can just try to do the `push` operation` again when saying "retry from the beginning".
If we retry from the beginning, why do we need to `restart` `self.guard` when the validation fails during the execution of `push`? Just it seemed to me that the flow is that we `restart` the guard to try do `push` again

**Comment by dnkim** [comment]
I believe professor initially said we should restart from the root, then corrected to that we also just can restart from the current node. However, I think retrying only `push` is not sufficient, you should restart from finding child.

**Comment by jeehoonkang** [comment]
I agree with @dnkim .

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have follow-up questions!
