### ISSUE TITLE
bst_stress

### ISSUE THREAD

**Issue by bprovot** [kaist-cp/helpdesk#121]
My bst_stress test always fails due to the same problem 
`running 2 tests

iteration 0: lookup("csYE3xmnKhgfuCqmBUxNGOqkldyl68MwK4Wx51mQtLmINcI1YbV6xroFj5FsBLwBk4Z5V9") (non-existing)

iteration 1: insert("4itlHOj1Bhp9awIDkWnFJXESoEdLOeYXJnsCNStFIgrrj8806KSvkF5NXESCY6Sn8eDVSMonipjuYw8O4Yv1Ni5H", 12051761944980166067)

iteration 2: lookup("nwhxdx9mfKsoMNhD7qeBqS8CZBwwogTSl3gFQF6ewLgdc2jhVsn2n5mSJJQvCdh6WJqbtRe4GHQr5pBc9") (non-existing)

thread 'bst_stress' panicked at 'assertion failed: (left == right)
  left: Some(12051761944980166067),
 right: None', tests\map_test.rs:78:17
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace.`

When it looks up for an existing value, the hashmap one seems not to exist if i understand well, but it was not removed from my bst at any moment in the previous iterations. What could be the problem ?

**Comment by tomtomjhj** [comment]
What about making a simpler but non-trivial test cases? Try extending `bst_smoke` test or [this](https://github.com/kaist-cp/helpdesk/issues/109#issuecomment-559819437).

**Comment by bprovot** [comment]
I already extended my bst_smoke and the problem seems to come only for this operation in bst_stress, and all the other ones seem to work just fine. I'm really wondering why this lmakes everything crash.

**Comment by jeehoonkang** [comment]
- It seems your `tests/map_test.rs:78` differs from mine.  Would you please `cargo update`?
- It seems `None` is the right value for iteration 2, because no values are inserted at its key ("nw...").  Actually, the value returned from your BST is for another key ("4it..."), right?

**Comment by bprovot** [comment]
I updated. Yes it seems I have a problem. I'm gonna try to fix that

**Comment by bprovot** [comment]
Yeah it was my bad, thank you.
