### ISSUE TITLE
What should find() pass as Dir parameter to push() when key == given key?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#123]
What should find() pass as Dir parameter to push() function when key == given key(cmp::Ordering::Equal case)? Or it doesn't matter which Dir parameter I pass to push() in that case?

**Comment by jeehoonkang** [comment]
It's "don't care" (https://en.wikipedia.org/wiki/Don%27t-care_term), i.e., either value is fine.

**Comment by jeehoonkang** [comment]
Closing it, but feel free to reopen it if you have follow-up questions!
