### ISSUE TITLE
How to tag pointer?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#124]
I am trying to tag pointer to the left child. I loaded left child, it is of type Shared. Then, I try to tag pointer in the following way: 
```guard.left.atomic_write(left_child.with_tag(1))```

However, I get ```expected struct 'crossbeam_epoch::atomic::Atomic', found struct 'crossbeam_epoch::atomic::Shared'``` error. Then, I tried getting left child as Atomic, however Atomic doesn't have ```with_tag```.
Thus, I am confused how can I tag pointer?

Thank you!

**Comment by bprovot** [comment]
Have you tried calling `load()`on your atomic ptr and make it a shared one ?

**Comment by Shynar88** [comment]
Yes, I wrote in the question: "...I loaded left child, it is of type Shared...."

**Comment by bprovot** [comment]
Oh sorry

**Comment by Shynar88** [comment]
Anyways, thank you for responding and trying to help!)

**Comment by qvntm** [comment]
To store `Shared` to `Atomic` use [store](https://docs.rs/crossbeam/0.7.3/crossbeam/epoch/struct.Atomic.html#method.store) function instead of `atomic_write` or `atomic_swap`

**Comment by jeehoonkang** [comment]
I agree with @qvntm .

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have follow-up questions!
