### ISSUE TITLE
[HW3] Question about cleaning up the slot

### ISSUE THREAD

**Issue by mjy0503** [kaist-cp/helpdesk#132]
By suggested procedures, we should clean up the slot after `thread::sleep`

So I re-load slot_ref to check the slot is collided and then use CAS to clean up.
However, I got a problem when CAS is failed.
what should we do it CAS is failed?

**Comment by dnkim** [comment]
It means the slot is collided (if the rest parts of the code is correct), so you should implement corresponding logics for the case.

**Comment by mjy0503** [comment]
@dnkim 
After `thread::sleep`,
If first load of slot_ref is tagged 1(or 2), but clean up CAS failed.
Then second load of slot_ref should be tagged 3.
Is it right?

**Comment by dnkim** [comment]
For `pop` (tagged 2), it is. However, for `push` (tagged 1), it is not. The second load could be tagged anything.
