### ISSUE TITLE
Scalability question

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#133]
In the slide 76 it is written: "Scalability: showing better performance as the # of **cores** grow." Is it cores, and not threads? Just in explanation it is written: "Reality: e.g. sublinear scaling after 16 threads"

**Comment by jeehoonkang** [comment]
In modern eras, core scalability is roughly equivalent to thread scalability, because their ratio is fixed at sillicon fabrication time (e.g. 2 hardware threads per core).

Closing, but feel free to reopen it for follow-up questions.
