### ISSUE TITLE
[HW2] Cannot return value from delete()

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#134]
In delete when I try to return old value, I get error. 
```
let prev_value = write_guard.value.as_ref();
// change write_guard.value here
return Ok(*(prev_value.unwrap()));
```

```
return Ok(*(prev_value.unwrap()));
 move occurs because value has type `V`, which does not implement the `Copy` trait
```
I tried clone(), and as_ref(), (*prev_value).unwrap() but always get different errors

How to return value from delete()?

**Comment by wns3645** [comment]
I also have this problem, too. :(

**Comment by dnkim** [comment]
`AtomicRW::atomic_swap` returns you the owner of the original value.

**Comment by Shynar88** [comment]
I tried to use it like this: ```return Ok(unsafe{(prev_value.atomic_swap(None)).unwrap()});``` but it returns error: ```expected type `V` found type `&V````. I tried as_ref() and '*', but it didn't help

**Comment by dnkim** [comment]
You don't need to `atomic_swap` on `prev_value` which is `Some(&V)`. Try on `write_guard.value`.

**Comment by Shynar88** [comment]
I changed prev_value to be ```let prev_value = write_guard.value;```, but it doesn't work because ```move occurs because value has type `std::option::Option<V>`, which does not implement the `Copy` trait```

**Comment by Shynar88** [comment]
I found a solution how to do it by ```core::ptr::read```, but still curious about ```atomic_swap``` version

**Comment by dnkim** [comment]
You should `atomic_swap` on `write_guard.value` directly, without assigning into another variable.

**Comment by Shynar88** [comment]
Got it. Thank you!!!
