### ISSUE TITLE
Why when we pop() from the queue we return next's value instead of popped value?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#136]
Why when we pop() from the queue we return next's value instead of popped node's value?
```return Some(ManuallyDrop::into_inner(ptr::read(&next_ref.data)))```

**Comment by dnkim** [comment]
Popped node is dummy node and `next` will be the next dummy node after `pop`.

**Comment by Shynar88** [comment]
Ok, got your point, thank you! But it is not clear for me at which moment the popped node turns into dummy?
```
if self
                .head
                .compare_and_set(head, next, Ordering::Release, guard)
                .is_ok()
            {
                unsafe {
                    guard.defer_destroy(head);
                    return Some(ManuallyDrop::into_inner(ptr::read(&next_ref.data)));
                }
            }
```
CAS makes head to point to the node to be popped(so it becomes dummy node for next pop's), ```guard.defer_destroy(head);``` destroys previous dummy, and then popped node's value is returned. However, for the popped value to become dummy it's data should become ```mem::uninitialized()```. Thus I am confused at which moment the popped node turns into dummy for next pops

**Comment by dnkim** [comment]
Implementation doesn't physically make the node into dummy. It only assumes that the node pointed by `head` is a dummy node.

**Comment by Shynar88** [comment]
@dnkim , thank you very much!!
