### ISSUE TITLE
Why tail pointer may be stale?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#137]
I think the answer is that "it can be stale, because we don't care about tail being the actual tail, as this and other threads can just move it(when it's stale) to the actual tail when necessary", but I am not sure.

**Comment by jeehoonkang** [comment]
In an MSQ, an enqueuer may push a node with a successful CAS, and after that, it fixes up the tail pointer.  In between, the tail pointer becomes temporarily stale and it's visible to the other threads.

Closing, but feel free to reopen it for follow-up questions.
