### ISSUE TITLE
Q on lecture slide 84

### ISSUE THREAD

**Issue by zoonoo** [kaist-cp/helpdesk#141]
I don't understand what the following quote exactly means on slide 84.

> Reads of R(2) and writes of W(2) should be “atomic” (no undefined behavior)

From what I've understood, it means that read/write of `seq` should be atomic.
What happens if it's not?
Could you elaborate on this sentence?

**Comment by choi7023546** [comment]
As I understand, it is same as "R(2) cannot read some values that W(2) wrote until all write operations of W(2) are done".  
fence(acquire) in read_validate will happen after self.seq.store(seq.wrapping_add(2), Ordering::Release), so R(2) can read W(2) values after writes of W(2) done atomically.
Am I right..?

**Comment by choi7023546** [comment]
As I understand, it is same as "R(2) cannot read some values that W(2) wrote until all write operations of W(2) are done".
Also, when reads of R(2) is in progress and W(2) happens, it will be invalidated by checking seq of R(2) and current seq of lock.
I'm not sure, sorry...

**Comment by zoonoo** [comment]
@choi7023546 

I understand what you mean, but I'm not sure if this sentence is referring to what you have described. That part is in some way described in the sentence just below on the same slide.
> R(2) may observe inconsistent state partially modified by W(2)
(R(2) needs to be resilient to such inconsistency)

**Comment by choi7023546** [comment]
Hmm.. than 
> Reads of R(2) and writes of W(2) should be “atomic” (no undefined behavior)
It is just a requirement and it can be achieved by release/acquire synchronization and release/acquire fence synchronization mentioned in the slide 84.
And this sentence explains, how it can be resolved? 
> R(2) may observe inconsistent state partially modified by W(2)

**Comment by jeehoonkang** [comment]
By "atomic" I mean reads and writes of a sequence lock-protected object, should be thread-safe in that no undefined behaviors should occur.  Sorry for confusion.  The word "atomic" means too many things...

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have follow-up questions!
