### ISSUE TITLE
Q from slide : What’s the motivation of Harris-Michael’s list?

### ISSUE THREAD

**Issue by zoonoo** [kaist-cp/helpdesk#142]
I'm sure this has been mentioned in the class.
Could anyone please explain?

**Comment by zoonoo** [comment]
I've noted that this was about applying reclamation scheme, but I don't understand exactly.

**Comment by jeehoonkang** [comment]
Hazard pointer doesn't support Harris-Michael's list.  (But it's not explained in the lecture.  If interested, please contact me.)
