### ISSUE TITLE
Question from slide - Page 102

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/helpdesk#143]
Hi.
I noted that the second question is about linearizability.
Is the first question also about linearizability?
Thanks.

**Comment by jeehoonkang** [comment]
https://docs.google.com/presentation/d/1NMg08N1LUNDPuMxNZ-UMbdH13p8LXgMM3esbWRMowhU/edit#slide=id.g742aa64bce_7_6

The two questions are related to safety and correctness (in particular, linearizability).  But we didn't discuss the details in the lecture.

**Comment by anemoneflower** [comment]
Thank you!
