### ISSUE TITLE
Strictly testing bst

### ISSUE THREAD

**Issue by alxest** [kaist-cp/helpdesk#145]
I am not taking the class but I am working on the homework.
It would be helpful if someone can elaborate a bit more on this comment: (https://github.com/kaist-cp/helpdesk/issues/109#issuecomment-559824194)
If such testing is actually implemented, can you include it in the repository?

Thanks a lot!

**Comment by jeehoonkang** [comment]
Unfortunately, I don't have a plan to upload a strict"er" test for BST.  The test we discussed in class is (1) logging each thread's actions, and (2) checking whether the logs are consistent.  The check is difficult to be complete because it's computation cost will be too high.
