### ISSUE TITLE
Are we expected to be able to make proves with operational semantics on the midterm?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#15]
The main content of today's video lecture was mainly IRIS operational semantics which is presented as an alternative to advanced separation logic semantics. The video lecture is in the scope of midterm exam as TA said. So, are we expected to be able to make proofs with various operational semantic variants presented in the lecture?

Thank you!

**Comment by jeehoonkang** [comment]
- Iris is not an operational semantics; it's a (program) logic.
- I'll not ask you to prove a complex thing from the ground up, but I'll possibly ask a few questions on proofs.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have followup questions.
