### ISSUE TITLE
Question for Coq (lf logic lemma_application_ex)

### ISSUE THREAD

**Issue by jmpasta** [kaist-cp/helpdesk#154]
I have a question for example `lemma_application_ex`.

I cannot understand the role of `proj1`.

```
proj1
     : forall P Q : Prop, P /\ Q -> P

In_map_iff
     : forall (A B : Type) (f : A -> B) 
         (l : list A) (y : B),
       In y (map f l) <->
       (exists x : A, f x = y /\ In x l)

Example lemma_application_ex :
  forall {n : nat} {ns : list nat},
    In n (map (fun m => m * 0) ns) ->
    n = 0.
Proof.
  intros n ns H.
  destruct (proj1 _ _ (In_map_iff _ _ _ _ _) H)
           as [m [Hm _]].
  rewrite mult_0_r in Hm. rewrite <- Hm. reflexivity.
Qed.
```

`(proj1 _ _ (In_map_iff _ _ _ _ _) H)` seems to be `(exists x : nat, (fun m : nat => m * 0) x = n /\ In x ns)`
And `apply In_map_iff in H` also concludes same result.
I think rather `destruct ((In_map_iff _ _ _ _ _) H)` makes sense. However, it is impossible.

I cannot understand that (1) how `proj1` takes 4 arguments (_, _, (In_map_iff ... ), H), although it takes only two arguments (P, Q) and (2) why `(proj1 _ _ (In_map_iff _ _ _ _ _) H)` is not `(exists x : nat, (fun m : nat => m * 0) x = n)` although `proj1` makes `P/\Q` to `P`.

**Comment by jeehoonkang** [comment]
- `proj1`'s third and fourth arguments seem to be `P /\ Q` and `In y (map f l)`.
- `((In_map_iff _ _ _ _ _) H)` is not a valid term because `<->` doesn't accept an argument.

I'm not sure it answers your question.  Please feel free to ask follow-up questions.

**Comment by jmpasta** [comment]
Thank you!
I forgot `A<->B` means `(A->B)/\(B->A)`.
`proj1` is used in quite tricky way in this example...
