### ISSUE TITLE
Can you give an example of a structure of the Cursor?

### ISSUE THREAD

**Issue by snyokang** [kaist-cp/helpdesk#16]
![image](https://user-images.githubusercontent.com/13789583/66886678-2f4b0000-f013-11e9-94e7-ccb12dd9ae13.png)

Hi.
I didn't get the concept of the cursor.
Can you show how the cursor struct will be where the cursor is placed in the purple line?

Is it okay to represent like below?
Cursor {
depth : 1,
parent : red node,
child : blue node,
index : 1,
length : 2,
}

Thank you.

**Comment by snyokang** [comment]
![image](https://user-images.githubusercontent.com/13789583/66887850-4ee42780-f017-11e9-9450-06ec7eb84a03.png)

Can I say the index is 2 in this case?

**Comment by jeehoonkang** [comment]
Yes, I think so.  It's the internal index used to specify which slot contains the child (=blue).

**Comment by snyokang** [comment]
Thanks a lot.
