### ISSUE TITLE
Questions about Coq tactic.

### ISSUE THREAD

**Issue by jmpasta** [kaist-cp/helpdesk#163]
I have some questions about coq tactics.

1. While proving the *progress* theorem in *StlcProp*(PLF), interesting usage of the `destruct` tactic appears.
```IHHt1: empty = empty -> value t1 \/ (exists t' : tm, t1 --> t')```
`destruct IHHt1` makes 3 branches, (1) `empty=empty`, (2) `value t1` (3) `(exists t':tm, t1 --> t')`
Does `destruct H` make branches `H1, H2, ... , Hn` if `H = H1 -> H2 -> ... -> Hn`?

2. I took a look at [this site](https://coq.inria.fr/refman/proof-engine/tactics.html#coq:tacn.destruct) to find a usage for the `destruct` tactic. I think this is the official site for coq. But, I had a problem to find an answer to my question 1, so are there any good sites to search for coq's gramma or usage?

3. While solving additional exercises (*stlc_variation*) in *StlcProp*, I had to check the theorem *preservation* still true for changed language.
```
Theorem preservation : forall t t' T,
  empty |- t \in T  ->
  t --> t'  ->
  empty |- t' \in T.
```
If it becomes false, I proved that `exists t t' T, (empty |- t \in T) /\ (t --> t') /\ ~(empty |- t' \in T)`.
For proving **negation** of `H1 -> H2 -> ... -> Hn`, I think there are two ways to prove (1) `~(H1 -> H2 -> ... -> Hn)`, or (2) `H1 /\ H2 /\ ... /\ Hn-1 /\ ~Hn`. I know these are logically equivalent, but I want to know which way is simple or recommended to prove by coq. Or is there another simple way to prove it?

**Comment by jeehoonkang** [comment]
1. yes.

1. yes, that's official.  sorry, I don't know where the behavior is described...  Googling "coq tactics cheat sheet" ring some bells, but I'm not sure how good they are.

1. (1) is recommended.  In fact, I think (2) is not equivalent to (1) in Coq without some excluded middle axioms or something like it...

1.

**Comment by jmpasta** [comment]
Thank you!
