### ISSUE TITLE
Question about tactic in coq

### ISSUE THREAD

**Issue by jmpasta** [kaist-cp/helpdesk#167]
I'm trying to solve exercises in the `Typechecking` chapter in PLF.

I found that the following equation appears frequently.
```
H: forall x, y = x -> P(x)
```
Obviously, P(y) is true.
I want to extract P(y) from H. 
If I create a new equation `H': y=y` with `assert`, I can do it by applying H to the equation H'
However, I think there is a more simple and clever way to do this such as using `Ltac`.
Is there any good way to do this?

**Comment by tomtomjhj** [comment]
https://coq.inria.fr/refman/proof-engine/tactics.html#coq:tacv.specialize

**Comment by jmpasta** [comment]
Thank you!
