### ISSUE TITLE
Question about coq (fresh and @).

### ISSUE THREAD

**Issue by jmpasta** [kaist-cp/helpdesk#174]
I am reading PE.v in PLF. When I read this chapter(line number 102~), I was confused about two things.

```
Tactic Notation "compare" ident(i) ident(j) :=
  let H := fresh "Heq" i j in
  destruct (eqb_stringP i j);
  [ subst j | ].

Theorem pe_domain: forall pe_st V n,
  pe_lookup pe_st V = Some n ->
  In V (map (@fst _ _) pe_st).
Proof. ~~~ Qed.
```
(1) What purpose of `let H := fresh "Heq" i j`? After I removed this part, the code totally works well.
(2) Why `(@fst _ _)` is used instead of `fst`? After I change it to `fst`, the code also works well.

Can you tell me the advantage of using these two things `fresh` and `@`?

**Comment by jeehoonkang** [comment]
- `fresh`: uh.. I don't know...
- `@fst`: probably the interpretation of `fst` differs if you turn on/off implicit argument settings. `@fst` works exactly the same regardless.
