### ISSUE TITLE
Why is the lookup function designed to return the input key?

### ISSUE THREAD

**Issue by snyokang** [kaist-cp/helpdesk#18]
Hi.

I am wondering that why the lookup function for the NodeBodyI returns the input key.

I think returning the reference to the node is enough because the caller knows the key already.

Can you explain please?

Thank you.

**Comment by jeehoonkang** [comment]
The returned `u8` value not the input key; it's the internal index used in `delete()`.

**Comment by snyokang** [comment]
Oh, I was confused by the same types. Thanks a lot.
