### ISSUE TITLE
Question about Entry & Cursor

### ISSUE THREAD

**Issue by mjy0503** [kaist-cp/helpdesk#21]
If I insert "FOO",  tree should have root node and leaf node only.

Then, I search "FO", Entry has

Cursor
- depth: 2
- parent: root
- child: leaf
- index: 0
- length: 2

Key: None

When lookup function evaluates, it should be failed.
Because child.header.length(3, "FOO") is not equal self.cursor.length(2, "FO")

What is wrong?

Thanks

**Comment by mjy0503** [comment]
I Add another question

I insert "FA", "FB". Tree has this shape.
                                      B
                F            --------------> N3
                             |        A
root ----------> N1 -------------> N2


I search "F", Entry is
Cursor
- depth:1
- parent:root
- child:N1
- index:0
- length:1

Key:None

When lookup function evaluates,
child.header.length(1, "F") is equal to self.cursor.length(1, "F")
and try to return body.

What is wrong in this case?

**Comment by jeehoonkang** [comment]
- I cannot understand your first question.  What are you asking for?
- `encode_key()` makes sure that a key should never be a prefix of another key.  So inserting `FA` and then looking up `F` is impossible.

**Comment by mjy0503** [comment]
Oh, I don't recognize about `encode_key()`
First case is similar as second one. "FO" is prefix of "FOO", so don't happen.

Thanks
