### ISSUE TITLE
Question in slide p.58 mutual exclusion

### ISSUE THREAD

**Issue by choi7023546** [kaist-cp/helpdesk#25]
I have a confusion with the meaning of 'mutual exclusion'
In this slide, does it mean same as '&self' that reference to the simultaneous writing of a memory address?

**Comment by jeehoonkang** [comment]
- Would you please repeat your question in Korean?
- FYI, mutual exclusion means at any moment of time, at most one thread is reading/writing to a data.

**Comment by choi7023546** [comment]
1. "mutual exclusion means at any moment of time, at most one thread is reading/writing to a data" 라면, 두 개 이상의 thread가 공유 메모리를 reading하는 것도 mutual exclusion에 해당하는 건가요?

2. Removing SMO를 한다는게, compare_and_swap 과 같은 rmw operation에 의해 한번에 하나의 thread만 writing을 할 수 있기 때문에 가능한 것인가요? 

+ ) 저 질문은 학기초에 SMS access safety를 설명하는 슬라이드와 헷갈려서 제가 잘못 생각했던 것 같습니다 ㅠㅜ

**Comment by choi7023546** [comment]
"mutual exclusion means at any moment of time, at most one thread is reading/writing to a data" 라면, 두 개 이상의 thread가 공유 메모리를 reading하는 것도 mutual exclusion에 해당하는 건가요?

Removing SMO를 한다는게, compare_and_swap 과 같은 rmw operation에 의해 한번에 하나의 thread만 writing을 할 수 있기 때문에 가능한 것인가요?

위의 질문은, fn lock(&self) 와 같은 인터페이스도 mutual exclusion과 상관이 있는건지 궁금합니다.

감사합니다!

**Comment by jeehoonkang** [comment]
1. Reading from multiple threads is not mutually exclusive.  (There are reader-writer locks that allows reading from multiple threads, but it's not called "mutual exclusion".)

2. RMW operations coordinate shared mutable operations, not eradicating them.  By "removing SMO" in that slide I meant literally removing SMOs by e.g. using locks.

3. The interface of `lock(&self)` means (1) lock itself is shared; but (2) if the call to `lock()` returns, you have an exclusive permission to read/write the underlying data, until you call `unlock()`.
