### ISSUE TITLE
CodeLLDB configuration

### ISSUE THREAD

**Issue by goodCycle** [kaist-cp/helpdesk#26]
While configure `CodeLLDB` in `launch.json` in `VSCode`(Mac OSX),
what is the proper path for `program`?
I configured `art/target/debug/deps/art_test-HASH`, but it does not work. (Process exited with code 101.)
Does of you succeed to configure `CodeLLDB` on `VSCode`, can you give me some help?
<img width="792" alt="스크린샷 2019-10-18 오후 12 04 55" src="https://user-images.githubusercontent.com/28590370/67063778-e45ff280-f1a2-11e9-9698-89a68d81c34b.png">

**Comment by jeehoonkang** [comment]
- Please paste code as text.
- I personally don't use vscode on macos...  I'd like to ask if anyone knows this issue.
- In the meantime, for interactive debugging, you may use CLion for the time being.

**Comment by goodCycle** [comment]
Okay, thanks. Can I open this issue until Sunday waiting for anyone who configures CodeLLDB?

**Comment by jeehoonkang** [comment]
Of course; not closing it because it's not resolved.

**Comment by drzix** [comment]
It works on my Mac. My settings are like below:

- I installed rust by command `curl https://sh.rustup.rs -sSf | sh`, not `brew install`.
- My lldb version is:
```
lldb-1100.0.28.19
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
```
- The path of my config json file is `~/cs492-concur/art/.vscode/launch.json`
- I tried to make my configuration file also use only the properties used by your configuration file:

```
{
   "version":"0.2.0",
   "configurations":[
      {
         "type":"lldb",
         "request":"launch",
         "name":"Debug",
         "program":"${workspaceRoot}/target/debug/deps/art_test-43b10f907c3e7b66",
         "args":[

         ],
         "cwd":"${workspaceRoot}"
      }
   ]
}
```

- Debugging process:
  1. Execute `cargo test`
  2. Copy the file name generated by the previous command. (`target/debug/deps/art_test-H@$H-H@SH`)
  3. Paste that path into `configurations[0].program`.


I think maybe you did it as same way, didn't you?
or **Didn't you install `Rust(rls)` on VS Code?**

**Comment by AnuarTB** [comment]
I think this might also help:
https://stackoverflow.com/a/52273254

**Comment by dkim** [comment]
When `launch.json` is not provided manually, the recent versions of CoreLLDB generate `launch.json` that automatically figures out the program path: https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#cargo-support The bad news is that LLDB's support for Rust on macOS is not so reliable yet: https://github.com/rust-lang/rust/issues/59907

**Comment by goodCycle** [comment]
Thanks, guys. It worked!
