### ISSUE TITLE
Question in ART delete operation

### ISSUE THREAD

**Issue by mjy0503** [kaist-cp/helpdesk#28]
1. by README.md, `You don’t need to shrink a node even if it’s underfull.`
It means empty node(has no children) can be exist?

2. `delete(...)` returns `Result<V, ()>`. But I can get only `&V` (or `&mut V`)
When I try to dereference it, `cannot move` error occurs.
Can you give me a hint about solving this problem?

**Comment by jeehoonkang** [comment]
- yes, you can leave empty nodes as is.
- You need to (1) copy the value in the tree, (2) forget about the value in the tree, and (3) return the copied value.  Does it help you..?

**Comment by mjy0503** [comment]
Can you give me more hint about (1) copy the value in the tree?
I think it cannot be copied because `V` doesn't have `Copy` trait.

**Comment by tomtomjhj** [comment]
Take a look at some unsafe functions in  `std::ptr`.

2019년 10월 19일 (토) 오후 12:04, JaeEui Ma <notifications@github.com>님이 작성:

**Comment by jeehoonkang** [comment]
Especially, look at `core::ptr::read()`

**Comment by Shynar88** [comment]
Could you, please, explain, what does "(2) forget about the value in the tree" mean? Thank you!

**Comment by jeehoonkang** [comment]
@Shynar88 see: https://doc.rust-lang.org/std/mem/fn.forget.html
