### ISSUE TITLE
Causality test case 11

### ISSUE THREAD

**Issue by mjy0503** [kaist-cp/helpdesk#29]
This is Causality test case 11
```
Initially, x = y = z = 0

Thread 1:
r1 = z
w = r1
r2 = x
y = r2

Thread 2:
r4 = w
r3 = y
z = r3
x = 1
```
x=1 can be certified in T2. But how can I certify y=1? 
I'm confused because T1 has no assignment, so it cannot certify anything alone.

**Comment by planetarynebula** [comment]
I think that certifying y=1 is possible after x=1 is certified. Because x=1 is certified (also re-certified), we can certify y=1 from y=r2=x=1.
Try promising semantics one-by-one. (x->y->z->w order)

**Comment by mjy0503** [comment]
Can I certify values sequentially?
If so, 
1) certify necessary values
2) real execution to re-certificate
is this correct step?

**Comment by planetarynebula** [comment]
I think so... And we need to re-certify all certified values again at each step.

**Comment by planetarynebula** [comment]
This is similar question for yours. #12

**Comment by jeehoonkang** [comment]
Like @planetarynebula said, please see #12 first, and ask follow-up questions if you have ones.
