### ISSUE TITLE
Causality test case 3 and 19

### ISSUE THREAD

**Issue by planetarynebula** [kaist-cp/helpdesk#30]
I have two questions about casuality test cases.

**Problem 3**

```
(Thread1)
r1 = x
r2 = x
if r1 == r2
  y = 1
```

```
(Thread3)
x = 2
```

y=1 can be certified from thread 1. But I confused by thread 3. We can certify the value, even though there is **message interleaving** from other thread. However, it is possible to y is not assigned to 1 due to thread 3. Doesn't this matter?

**Problem 19**

This problem is the same as test case 17, except that thread 1 has been split into two threads. I think that **join thread** plays a similar role as SC fence, but I don't know how it is impossible to recertify. Why is it disallowed by promising semantics?

**Comment by planetarynebula** [comment]
I found that problem #19 is already asked in the other question, so please ignore the question #19.

**Comment by jeehoonkang** [comment]
On test case 3: Thread 1 is able to read different values from x for r1 and r2 thanks to Thread 3, but Thread 1 is also able to read the same value from x for r1 and r2.  Certification requires the ability---not necessity---to fulfill the thread's promises, and the promise to write y=1 is justified by the certification in which Thread 1 reads the same value from x for r1 and r2.

**Comment by efenniht** [comment]
FYI, my interpretation of "join thread" is:
```
join thread 2                     || x = 1
r1 = x
~>
while (t.load(acquire) == 0) {}   || x = 1
r1 = x                            || t.store(1, release)
```
where `t` is initialized with 0.

**Comment by drzix** [comment]
@efenniht
You mean, of course, "where `t` is also a **unique** virtual variable that only exists on the pair of joinee-joiner threads?

**Comment by efenniht** [comment]
@drzix, I think it's enough that such `t` exists for each joinee thread:
```
a = 1 || join thread 1 || join thread 1
~>
a = 1                || while (t.load(acquire) == 0) {} || while (t.load(acquire) == 0) {}
t.store(1, release)
```

**Comment by drzix** [comment]
@efenniht
Actually I meant maybe there shoud be a constraint that `t` **cannot be writable** on the other threads, but yes, I agree with you!
