### ISSUE TITLE
Guaranteeing fairness by waiting w/ different locations?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#31]
It is written "Guaranteeing fairness by ordering & waiting w/ different locations"(slide 70). However, I thought that fairness is achieved only by ordering. Could you, please, explain how fairness is achieved by waiting w/ different locations? Thank you!

**Comment by jeehoonkang** [comment]
Yes, fairness is achieved by the ordering instruction (fetch-add or swap).  By the sentence, I meant the location for ordering and that for waiting are different.
