### ISSUE TITLE
Question about NodeBody256

### ISSUE THREAD

**Issue by mjy0503** [kaist-cp/helpdesk#34]
This is impl of NodeBody256's lookup method.
```
impl<V> NodeBodyI<V> for NodeBody256<V> {
    fn lookup(&self, key: u8) -> Option<(u8, &NodeBox<V>)> {
        Some((key, unsafe {
            self.children.get_unchecked(usize::from(key))
        }))
    }
}
```
I think this lookup function should return None when there's no child.
But it returns always Some. Is this expected behavior?

**Comment by tomtomjhj** [comment]
node256 always contains any key(that  may point to a null node) but smaller
nodes may not have the given key itself.


2019년 10월 19일 (토) 오후 9:51, JaeEui Ma <notifications@github.com>님이 작성:

**Comment by mjy0503** [comment]
For clarification, I should check `NodeBox::is_null()` when `Some` type is returned. Is it right?

**Comment by tomtomjhj** [comment]
Yeah.

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/cs492-concur/issues/6#issuecomment-545944595
Oh that was a bug actually.

**Comment by jeehoonkang** [comment]
Sorry, I just noticed this and fixed the bug.
