### ISSUE TITLE
Questions about Peterson's mutex

### ISSUE THREAD

**Issue by efenniht** [kaist-cp/helpdesk#37]
I have a few of questions about Peterson's mutex.

```rust
static flag: [AtomicBool; 2];
static turn: AtomicUsize;

fn begin(id: usize) {
    flag[id].store(true);
    fence(SeqCst);    // A
    turn.store(1 - id);
    fence(SeqCst);    // B

    while flag[1 - id].load(acquire) && turn.load() == 1 - id {}    
}

fn end(id: usize) {
    flag[id].store(false, release);
}
```
1. Some ordering of operations are omitted. Are all of them `relaxed`?

2. If so, why `turn` should be atomic? Just for avoiding `unsafe`?

3. What does make compiler not to optimize `turn.load() == 1 - id` into `true`? I suspect that readonly reference to `turn`, which has interior mutability makes reading `turn` be volatile. If so, suppose this code is rewritten in C. Then do I need to denote `turn` by volatile?

4. I conject that fence B ensures `turn.load()` to read the latest message of `turn`. But I think this is unnecessary, since `turn.store(1 - id)` cannot be reordered after `turn.load()`. Looking at spinlock, it does not ensures compare-and-swap reads the latest flag. Is there another reason for fence B?

**Comment by jeehoonkang** [comment]
1. Yes, let's say it's relaxed if omitted.
2. It may actually be written by multiple threads at the same time.  If it were nonatomic, the behavior is undefined and compilers may compile it into an unsafe implementation of Peterson's mutex.
3. Atomic load, even if it's relaxed, is not usually optimized away.  In particular, the store forwarding optimization doesn't kick in for atomic loads.
4. Fence B is necessary.  In essence, `turn.store()` may be reordered with `flag[1 - id].load(acquire)`.  I believe you can find a counter-example of  mutual exclusion in the promising semantics, too.

**Comment by efenniht** [comment]
2. So do you mean race of two threads to write on one variable is not only nondeterministic, but also undefined?

**Comment by jeehoonkang** [comment]
Yes, it's undefined.  The reason is compilers assume nonatomic writes are not concurrently written by other writes and perform aggressive optimization.

**Comment by efenniht** [comment]
I found that a similar question was there: https://stackoverflow.com/a/28591924
