### ISSUE TITLE
Cursor Function of the ART

### ISSUE THREAD

**Issue by bprovot** [kaist-cp/helpdesk#38]
I don't really understand the goal of the Cursor function in this case. I understand how the cursor is built but I can't understand what it should do in this case. Is the goal to iterate on the tree here to return the cursor associated with a key ?

**Comment by jeehoonkang** [comment]
- A cursor is meant to point to a point (which is either the node or on an edge) in the tree.
- What do you mean by the "cursor function"?  Please refer to the lines of code in GitHub.

**Comment by Shynar88** [comment]
I guess it's line 110 from art.rs. I also don't understand the goal of this function.

```
fn cursor<'a, I>(&'a mut self, key: &mut Peekable<I>) -> Cursor<'a, V>
    where
        I: 'a + Iterator<Item = u8>,
    {
        unimplemented!()
    }
```

**Comment by jeehoonkang** [comment]
- You can point to the code like this: https://github.com/kaist-cp/cs492-concur/blob/afc09d9e0c532ded69d1c6d2a2420f74ebc38f79/art/src/art.rs#L110-L115

- It's meant to return the cursor corresponding to the given `key`.

**Comment by bprovot** [comment]
Ok then I'm not sure to understand what a cursor pointing to an edge is. Could you please illustrate ?

**Comment by Shynar88** [comment]
Maybe #16 can help? As far as I understood, the purple line is the cursor pointing to the edge

**Comment by bprovot** [comment]
OK this helped. Thanks a lot
