### ISSUE TITLE
Getting a value from a nodebox ART

### ISSUE THREAD

**Issue by bprovot** [kaist-cp/helpdesk#40]
I'm wondering how to collect the value out from a nodebox. I'm currently trying by calling '''body.right().unwrap()''' but it says 

"cannot move out of a mutable reference

move occurs because value has type `V`, which does not implement the `Copy` trait"

How do i get around this ?

**Comment by bprovot** [comment]
I'm wondering how to collect the value out from a nodebox. I'm currently trying by calling `body.right().unwrap()` but it says

> "cannot move out of a mutable reference
> 
> move occurs because value has type V, which does not implement the Copy trait"

How do i get around this ?

**Comment by bprovot** [comment]
So the question is actually how to get a value from a reference to a mutable value.

**Comment by tomtomjhj** [comment]
https://github.com/kaist-cp/helpdesk/issues/28#issuecomment-544070225

**Comment by bprovot** [comment]
Ah I was sure i was that somewhere ! Thanks a lot !
