### ISSUE TITLE
Growing nodes

### ISSUE THREAD

**Issue by ChristPi** [kaist-cp/helpdesk#42]
How do you grow a full 256-Node? Do we create the node above the root to fit the extra node(special case due to path compression)?

**Comment by planetarynebula** [comment]
Do you mean that a node can have more than 256 childrens? It is impossible because the key of a node is 1byte value(u8) and it is in the range of 0 to 255.

**Comment by ChristPi** [comment]
I mean the special case with path compression. Do you have to consider the edge case where you have to make a node above the root?

**Comment by planetarynebula** [comment]
Path compression means that removing all inner nodes that have only a single child. And it doesn't remove root node. Why we should make a node above the root? It's hard to imagine the case what you are saying... I think that it never happens.

**Comment by ChristPi** [comment]
"Another special case occurs if the key of the new leaf
differs from a compressed path: A new inner node is created
above the current node and the compressed paths are adjusted
accordingly (lines 17-24)" - ART paper
That would mean if the root is full of compressed path keys that you would have to create a node above the root. So my question is if this is part of the assignment as well?

**Comment by dnkim** [comment]
Path compression has nothing to do with the root. The header length of the root is always 0. If a value with key "AA" is inserted into an empty tree, it will be a child of root with header length 3 ("AA$").

**Comment by ChristPi** [comment]
ok now I am even more confused, I thought that you have the keys in the node(root) to search through the tree. So the root is a no-key 256-node which is not an inner node? What is the difference between the root and a standard 256-node? Do you have to do extra handling for searching in the root?

**Comment by dnkim** [comment]
The key is stored scatteredly in the tree. `keys` in `NodeBody` is for searching the child and `key` in `NodeHeader` is for path compression. If key "ABCDEFGHI" is inserted into the tree whose value for `MAX_LENGTH` in `NodeHeader` is 4 (which is 23 in our actual ART), the tree will be like:

root (`key`: "", `keys`["A"]: node0)
|
node0 (`key`: "AB", `keys`["C"]: node1)
|
node1 (`key`: "CDEF", `keys`["G"]: node2)
|
node2 (`key`: "GHI$", value: 42)

You can find out that the value for key "ABCDEFGHI" is 42 by traversing the tree.

**Comment by ChristPi** [comment]
Ok then I have missinterpreted the role of the keys in the nodebody. Thank you for clearing this up for me.
