### ISSUE TITLE
Specification of the Entry API

### ISSUE THREAD

**Issue by AnuarTB** [kaist-cp/helpdesk#44]
In the code there was a [link](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html) to the Entry API. I have read the documentation and have observed some misalignments in design between their and ours implementation. To elaborate:

1) The specification of the `entry` function ([here](https://github.com/kaist-cp/cs492-concur/blob/master/art/src/art.rs#L118-L125)) in the implementation of ART I think is incorrect. We create a new entry every time we refer to some key. In the standard library, if the entry associated with the key is already there, the function just returns it.

2) The Entry in standard library, is actually a enum consisting of two states: Vacant and Occupied. Do we have to implement it in a similar way?

Could you please clarify my doubts?

Thanks!

**Comment by jeehoonkang** [comment]
I referred the link to facilitate your understanding of the API, but as you said, the skeleton code's API is different from the standard library's.

1. Yes, they differ in their behavior.
2. No, you don't have to follow the standard library's implementation.

**Comment by AnuarTB** [comment]
1. Can you please elaborate on that? In your code you use it as though it complies to standard library implementation design. For example, in your implementation of `SequentialMap` Trait you use `entry` [method](https://github.com/kaist-cp/cs492-concur/blob/master/art/src/art.rs#L134-L137) for deleting the key.  However, from the skeleton code it seems that you create a new entry from this key and try to delete it, which seems illogical to me. Can you please explain how do we have to use your API? 
2. Ack

P.S. I think it would be great to write a homework guideline to explain the design of your skeleton code. (For the next homework as well) Personally, I thought that if you have left the link in the code, then it means that your code will comply to API specification as it is written in the doc. I couldn't understand your API and had to dig for hours into rust-lang source codes to find this misalignment.

**Comment by jeehoonkang** [comment]
- Probably I don't understand your question..  In the skeleton code, `SequentialMap::delete()` finds the corresponding entry, and then calls `Entry::delete()`, which tries to delete the value.  Would you please explain further which part of the implementation is illogical?

- I agree that a more detailed guideline is helpful for the students to implement the homework.  But I intended it to be more open-ended.  (Even, the homework specifically says the `Art` type should not be changed, but you can completely remove the entry API and implement `SequentialMap` methods on your own.)  That's because in practice you will usually not be able to access a detailed specification before implementing something...

**Comment by AnuarTB** [comment]
I mean if the entry function is shallow, wouldn't it be more logical to implement the functionality in `SequentialMap` i.e. delete the node right in the ART. Furthermore, the `struct entry` has no access to `root` of ART, which makes it more difficult to delete the key from the tree.

**Comment by jeehoonkang** [comment]
Ah, I see.   You can think of entry API a lower-level API, and SequentialMap a higher-level API.

**Comment by AnuarTB** [comment]
> Ah, I see. You can think of entry API a lower-level API, and SequentialMap a higher-level API.

The last thing that I don't understand is the need of `cursor` in the Entry API. Can you also explain its purpose there?

**Comment by jeehoonkang** [comment]
- `cursor` is pointing to a point in an edge or a node inside the tree.
- The purpose of `cursor` is specifying the location for which the value is queried, a new value is inserted, or an existing value is removed.
