### ISSUE TITLE
Question about NodeBodyI's lookup function

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/helpdesk#45]
Hi. in lookup function in NodeBodyI, It uses 'key'.

```
pub trait NodeBodyI<V> {
    /// Lookups the child of `key`.
    ///
    /// Returns `Some((i, n))` if `n` is the child of `key` at the internal index `i`.
    fn lookup(&self, key: u8) -> Option<(u8, &NodeBox<V>)>;

    ...
```

I'm confused of 'key' in this function.
If I have whole key "BAR", and search it at root NodeBox's Body, does it search about key "BAR" or just a fragment of key "B"? I think both case return index of 'B', but confusing of "child of 'key'". Is it leaf node of "BAR" or internal node under the index of 'B'?

![image](https://user-images.githubusercontent.com/31069340/67632741-ecc6d480-f8ea-11e9-82c7-f6f77aad5089.png)

**Comment by planetarynebula** [comment]
Every NodeBodyI contains only 1btye keys, so it search about just "B". After it finds a child node with key "B", then child node's header contains whole key "BAR". So you need to check it to ensure that you find the correct child.

The function [new_path](https://github.com/kaist-cp/cs492-concur/blob/master/art/src/node.rs#L454-L462) in NodeBox will help you to understand.

**Comment by anemoneflower** [comment]
Thanks!! It really helped :)
