### ISSUE TITLE
How to use into function in NodeBox?

### ISSUE THREAD

**Issue by planetarynebula** [kaist-cp/helpdesk#48]
There is a `into` function for NodeBox which consumes itself and return tuple `(NodeHeader, Vec<(u8, NodeBox<V>)>)` [link](https://github.com/kaist-cp/cs492-concur/blob/master/art/src/node.rs#L498-L504). I want to use this function but I cannot use this.

When I use it for child field in Cursor struct, it gives me an error like this:
the trait `std::convert::From<&mut node::NodeBox<V>>` is not implemented for `(node::NodeHeader, std::vec::Vec<(u8, node::NodeBox<V>)>)`

I used it like this: `let t: (NodeHeader, Vec<(u8, NodeBox<V>)>) = self.cursor.child.into();`
`let (header, children) = self.cursor.child.into();` doesn't work, too. 

The compiler cannot find the function `fn into(mut self) -> (NodeHeader, Vec<(u8, NodeBox<V>)>)`.

**Comment by tomtomjhj** [comment]
`into` takes the ownership of the `NodeBox`. Note that you can't take the ownership of `*self.cursor.child` without doing something special.

**Comment by planetarynebula** [comment]
I found that copying NodeBox with ptr::read works. Does it free from memory issues? Since `into` function drops itself (NodeBox), I wonder if there are any side effects of dropping the copied NodeBox.

**Comment by tomtomjhj** [comment]
`ptr::read` is basically a shallow copy. Up to my knowledge, if the copied value contains pointers (or things that can be considered as pointers) and its `Drop` instance does something more than freeing the memory block for the value itself (e.g. follow the pointers to recursively drop more values, like `NodeBox`), dropping the value may cause double free when the source value gets dropped. 

You can prevent this by `mem::forget` or `ptr::write` but I think it adds unnecessary complications in this case. A safer solution is to use `mem::replace` with a default value, which allows you to trade(?) the ownerships. There are several uses of `mem::replace` in `node.rs`.

Also take a look at my comment and @efenniht's comment in https://github.com/kaist-cp/cs492-concur/pull/15#pullrequestreview-307522075 for the use of `mem::forget`. Also note that `mem::forget` is not an unsafe function.

**Comment by planetarynebula** [comment]
Thank you so much!

**Comment by planetarynebula** [comment]
I found that using `ptr::read` causes some double free errors. I think it is good to use `mem::replace(self.cursor.child, NodeBox::null())` to get ownership of `self.cursor.child`.
