### ISSUE TITLE
function that takes the ownership doesn't actually take the ownership when given a mutable reference

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/helpdesk#5]
[`collect`](https://doc.rust-lang.org/core/iter/trait.Iterator.html#method.collect) function takes the ownership of the iterator and returns the collection of items in the iterator.
So following program should not compile:
```rust
fn main() {
    let a = vec![1, 2, 3];
    let i = &a.iter();
    let b = i.collect::<Vec<_>>();
    println!("{:?}, {:?}", i, b);
}
```
indeed, the error msg is exactly what we would expect:
```
error[E0507]: cannot move out of `*i` which is behind a shared reference
  --> src/main.rs:41:13
   |
41 |     let b = i.collect::<Vec<_>>();
   |             ^ move occurs because `*i` has type `std::slice::Iter<'_, i32>`, which does not implement the `Copy` trait
```
but if I make a small modification:
```rust
fn main() {
    let a = vec![1, 2, 3];
    let i = &mut a.iter(); // & to &mut
    let b = i.collect::<Vec<_>>();
    println!("{:?}, {:?}", i.next(), b); // use &mut again
}
```
it compiles and prints `None, [1, 2, 3]`. 
How is this possible?

**Comment by tomtomjhj** [comment]
this one doesn't compile, which is the expected behavior
```rust
fn main() {
    let a = vec![1, 2, 3];
    let i = &mut a.iter();
    drop(i);
    println!("{:?}", i.next());
}
```
```
error[E0382]: borrow of moved value: `i`
  --> src/main.rs:43:22
   |
40 |     let i = &mut a.iter();
   |         - move occurs because `i` has type `&mut std::slice::Iter<'_, i32>`, which does not implement the `Copy` trait
41 |     // let b = i.collect::<Vec<_>>();
42 |     drop(i);
   |          - value moved here
43 |     println!("{:?}", i.next());
   |                      ^ value borrowed here after move
```

**Comment by jeehoonkang** [comment]
Thank you for bringing up an important and difficult question.  Honestly I don't know the answer yet.  I'll try hard to figure out what's going on your examples.  Sorry for not answering your question now.

**Comment by youknowone** [comment]
The value correctly moves without mutable borrow

```rust
fn main() {
    let a = vec![1, 2, 3];
    let mut i = a.iter(); // & to &mut
    let b = i.collect::<Vec<_>>();
    println!("{:?}, {:?}", i.next(), b); // use &mut again
}
```

```
error[E0382]: borrow of moved value: `i`
 --> t.rs:5:28
  |
3 |     let mut i = a.iter(); // & to &mut
  |         ----- move occurs because `i` has type `std::slice::Iter<'_, i32>`, which does not implement the `Copy` trait
4 |     let b = i.collect::<Vec<_>>();
  |             - value moved here
5 |     println!("{:?}, {:?}", i.next(), b); // use &mut again
  |                            ^ value borrowed here after move

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.
```

**Comment by HyeonuPark** [comment]
There's `impl<'a, I: Iterator> Iterator for &'a mut I {...}` in std. So `&mut (a.iter())` itself is a iterator, you can call `.collect()` on it.

https://doc.rust-lang.org/std/iter/trait.Iterator.html#foreign-impls

**Comment by tomtomjhj** [comment]
@HyeonuPark thank you for the [answer](https://doc.rust-lang.org/src/core/iter/traits/iterator.rs.html#2704-2711).
That explains `i.collect()` but I'm still not sure why it's possible to use `i` again.
`i` itself moved into `collect` so I think using `i` after `collect()` is not allowed.

A plausible explanation is that `&mut i: &mut &mut Iter<...>` (instead of `i`) is moved into `collect` since `I:Iterator` implies `(&mut I):Iterator` which in turn implies `(&mut (&mut I)):Iterator`. 
This at least doesn't seem to violate the method resolution rule but makes me wonder how rustc handles this kind of things.

**Comment by dkim** [comment]
```
let i = &mut a.iter();
let b = i.collect::<Vec<_>>();
```
is transformed into
```
let i = &mut a.iter();
let b = Iterator::collect::<Vec<_>>(&mut *i); // `&mut *i` is moved instead of `i`.
``` 
by an automatic [**reborrowing**](https://stackoverflow.com/a/45104627/).

**Comment by tomtomjhj** [comment]
@dkim thank you for the answer. That explanation totally makes sense, but it doesn't seem to precisely match the [mir output](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=6fbf4bd4abefea48b09145365a50320d). Here is the excerpt:
```rust
    ...
    scope 1 {
        let mut _5: std::slice::Iter<i32>; // "iii" in scope 1 at src/main.rs:3:9: 3:16
        scope 2 {
            let _9: &mut std::slice::Iter<i32>; // "rrr" in scope 2 at src/main.rs:4:9: 4:12
            scope 3 {
                let _10: std::vec::Vec<&i32>; // "_bbb" in scope 3 at src/main.rs:5:9: 5:13
                scope 4 {
                }
            }
        }
    }
    ....
    bb3: {
        _6 = _7;                         // bb3[0]: scope 1 at src/main.rs:3:19: 3:22
        StorageDead(_8);                 // bb3[1]: scope 1 at src/main.rs:3:21: 3:22
        _5 = const core::slice::<impl [i32]>::iter(move _6) -> [return: bb5, unwind: bb4]; // bb3[2]: scope 1 at src/main.rs:3:19: 3:29
    }
    ...

    bb5: {
        StorageDead(_6);                 // bb5[0]: scope 1 at src/main.rs:3:28: 3:29
        StorageDead(_7);                 // bb5[1]: scope 1 at src/main.rs:3:29: 3:30
        StorageLive(_9);                 // bb5[2]: scope 2 at src/main.rs:4:9: 4:12
        _9 = &mut _5;                    // bb5[3]: scope 2 at src/main.rs:4:15: 4:23
        StorageLive(_10);                // bb5[4]: scope 3 at src/main.rs:5:9: 5:13
        StorageLive(_11);                // bb5[5]: scope 3 at src/main.rs:5:16: 5:19
        _11 = _9;                        // bb5[6]: scope 3 at src/main.rs:5:16: 5:19
        _10 = const <&mut std::slice::Iter<i32> as std::iter::Iterator>::collect::<std::vec::Vec<&i32>>(move _11) -> [return: bb6, unwind: bb4]; // bb5[7]: scope 3 at src/main.rs:5:16: 5:39
        ...
    }

    bb6: {
        StorageDead(_11);                // bb6[0]: scope 3 at src/main.rs:5:38: 5:39
        StorageLive(_12);                // bb6[1]: scope 4 at src/main.rs:6:5: 6:15
        StorageLive(_13);                // bb6[2]: scope 4 at src/main.rs:6:5: 6:8
        _13 = _9;                        // bb6[3]: scope 4 at src/main.rs:6:5: 6:8
        _12 = const <std::slice::Iter<i32> as std::iter::Iterator>::next(move _13) -> [return: bb7, unwind: bb8]; // bb6[4]: scope 4 at src/main.rs:6:5: 6:15
        ...
    }
```
 `collect` uses `_11` and `next` uses `_13`. `_11` and `_13` are basically copies[1] of  `_9 = &mut _5`. 
If reborrowing had actually happened, then `collect` and `next` should've produced their own  `&mut _5`.

[1]: Assuming that `_11 = _9` is a copy assignment (instead of move) and `&mut _` is a copyable thing in mir (which isn't true in rust frontend)

**Comment by dkim** [comment]
`_11` and `_13` can be understood as "their own `&mut _5`" that are generated by reborrowing, can't they? In other words, it seems to me that reborrowing is implemented at the level of MIR by allowing those copies of mutable references (possibly, under some special conditions). Also, it might be worth noting that the borrow checker worked on the abstract syntax tree before the NLL checker was introduced. 

Incidentally, you might be interested to know that

```rust
 let mut x = 0;
 let y = &mut x;
 let z = y;
 println!("{}", z);
 println!("{}", y);
```
does not compile, as expected, while
```rust
 let mut x = 0;
 let y = &mut x;
 let z: &mut _ = y;
 println!("{}", z);
 println!("{}", y);
```
DOES compile.

**Comment by tomtomjhj** [comment]
@dkim I guess you're right about the implementation of reborrowing. 
So the latter one is basically equivalent to 
```rust
 let mut x = 0;
 let y = &mut x;
 let z = &mut *y;
...
```
MIR output is almost identical except
```
<  let _3: &mut i32 as UserTypeProjection { base: UserType(0), projs: [] }; // "z" in scope 2 at src/main.rs:4:9: 4:10
---
>  let _3: &mut i32;
``` 
So rustc seems to do reborrowing iff there is a context that expects a specific type e.g. function parameters, type annotation, etc.

Thanks a lot!

Here is the [summary](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a0a7c3bf2b1db733dbc60e12b20eeae0).

**Comment by tomtomjhj** [comment]
So it seems that there may exist multiple mutable references (implemented as copy in mir as above) of an object if some conditions are met. I guess the [stacked borrow stuff](https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md) is related to this.

**Comment by jeehoonkang** [comment]
@youknowone @HyeonuPark @dkim @tomtomjhj Thank you for a very enlightening discussion.  Thanks to this discussion, I got to know more about Rust.
