### ISSUE TITLE
How to use new_path function?

### ISSUE THREAD

**Issue by lhw941** [kaist-cp/helpdesk#50]
I want to use `NodeBox::new_path` function in the method of `Entry` Struct, but `Entry` has key whose type is `Peekable<I>` , while `new_path` function needs key whose type is `I` with trait `DoubleEndedIterator`. Although Entry struct has trait bound of type I, it seems that `Peekable<I>` lose such trait. So it's impossible to call `new_path` function with element `key` in `Entry`. How can I solve this problem?

**Comment by tomtomjhj** [comment]
https://doc.rust-lang.org/src/core/iter/adapters/mod.rs.html#1195-1231
`I: DoubleEndedIterator` implies `Peekable<I>: DoubleEndedIterator` so it should be fine. Try upgrading your rust version. I ran into similar problem with `nightly-2019-07-31` and it was resolved by upgrading to `nightly-2019-10-04`.

**Comment by lhw941** [comment]
Thank you so much! Yes it's very unintuitive that Peekable doesn't have such Trait :)
