### ISSUE TITLE
Question about new_path function.

### ISSUE THREAD

**Issue by planetarynebula** [kaist-cp/helpdesk#51]
I am implementing `or_insert_with` function. This function returns `Ok(&mut V)` if insertion succeeds. And I got trouble to returning this mutable reference of V. I created new nodes with `new_path` function, but it gives `*const V` so that I cannot make it mutable. In [`new_path` function](https://github.com/kaist-cp/cs492-concur/blob/master/art/src/node.rs#L456), a `result` variable is type casted by *const V although it can be casted by *mut V. Why `new_path` does not return `*mut V`? If I change `new_path` function to return `*mut V`, I can return `Ok(&mut V)` easily. Does it have a problem? Is there a reason for returning `*const V` in `new_path` function?

**Comment by qvntm** [comment]
You can do something like `unsafe{&mut *(vptr as *const _ as *mut V)}` to convert `*const V` to `&mut V`.

**Comment by planetarynebula** [comment]
Oh, I didn't know the way! Thank you.

**Comment by tomtomjhj** [comment]
Just in case if you are interested in the difference b/w `*const T` and `*mut T`:
https://internals.rust-lang.org/t/what-is-the-real-difference-between-const-t-and-mut-t-raw-pointers/6127
