### ISSUE TITLE
Returning Err(V,F) in or_insert_with

### ISSUE THREAD

**Issue by lhw941** [kaist-cp/helpdesk#52]
Hi. I'm now trying to implement `or_insert_with`, which has parameter `f:F` and return error type with such f. I think it's inevitable to call or consume the f in the `or_insert_with`. However, then it's impossible to return the f. Here's the trick I try to use.

1. Instead of return f, I store val=f() and try to return closure `| | {val}` . But compiler said it's not an type F. 

2. Just like other cases, I try to use trick to unsafely move the value without changing ownership using raw pointer, but because f if function, I cannot apply the technique I used for other normal variable. 

How can I deal with this problem??

**Comment by jeehoonkang** [comment]
Why `f` should be called?  You can call it only when you need to.

**Comment by lhw941** [comment]
I want to call `new_path` function in `or_insert with`. If I try to use `f` as parameter, then it is consumed. If I try to use closure such as `| | {val}` to call `new_path` , then I have to call `f` to know the value. Do I try to design function in completely wrong way?

**Comment by qvntm** [comment]
Since you don't have to change the value during insertion, I don't think you need to consume it outside `new_path()`.

**Comment by jeehoonkang** [comment]
I'm closing it, but feel free to reopen it for follow-up questions!
