### ISSUE TITLE
Clarification on tree structure during insertion

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#55]
I am confusing about the restructuring and exact structure of the tree. Could you, please, check if I draw the structure of tree correctly after each operation? Thank you!

https://drive.google.com/file/d/1YG_rDZPuHewEu07mM5_25I8KcEZnJd9E/view?usp=sharing

**Comment by jeehoonkang** [comment]
At a high level, it seems correct.  (I cannot verify the details are okay because it's not clearly written in the drawing...)

**Comment by Shynar88** [comment]
Tree after following operations: insert("AA", 2), insert("AB", 3), insert("A", 1)
![72944050_948353672207849_9069141891559194624_n](https://user-images.githubusercontent.com/38908309/68064951-c202d300-fd65-11e9-9db8-31254292dca1.jpg)
In case that structure is correct, there is such huge inconsistency(that key endmark can lead to leaf type node and ordinary character can lead to leaf type node). Currently my searching algorithm for cursor relies on reaching key endmark in its key iterator for knowing at which node to stop. In case we query AA, relying on reaching key endmark in key iterator will result in successful extraction of value from node AA.  But, in case of querying 'A', this will not work(because we will reach key endmark at the time we are at node A which is not the leaf type), in order to successfully reach leaf type node, we have to search through node's children to find key endmark. But even if I implement searching through node's children to find key endmark when key iterator reaches endmark, then it will not work for 'AA' case, as when key iterator reaches endmark, we will be already in the leaf type node which doesn't have children through which to iterate.
I was working on stopping criteria for two days(( I still think that my understanding of tree structure is incorrect. Could you, please, recheck my tree drawing, specifically the leaf nodes part. Thank you!

**Comment by LockOne** [comment]
I'm no TA, I'm just one of your classmates.
I'm not sure what's the problem on the above example.
Both ordinary keys (like 'A'(65 in ASCII),'B'(66)) or endmark (which is 255) can be a key to children,
and the structure on the picture looks good.
If you want to lookup with key ['A'], Art converts it to bytes array [65, 255].
On the root, it will use 65 as key to find node A,
on node A, you can use 255 to find the middle nodeboxV.

**Comment by jeehoonkang** [comment]
I agree with @LockOne, thank you!  I'm closing it, but feel free to reopen it for follow-up questions.
