### ISSUE TITLE
Homework assignment submission method

### ISSUE THREAD

**Issue by lumiknit** [kaist-cp/helpdesk#56]
How can I submit art.rs?

**Comment by zoonoo** [comment]
Does anyone have any update on this?

**Comment by jeehoonkang** [comment]
Sorry for late response.  Because of the powerout at KAIST, I feel obliged to extend the deadline by 12 hours.  The new deadline will be 9pm, Monday.  I'll explain how to submit your homework at Monday's class.

**Comment by jeehoonkang** [comment]
https://github.com/kaist-cp/cs492-concur/issues/6#issuecomment-549165609
