### ISSUE TITLE
Confusion on "store hoisting"

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#6]
On slide 31, it's hard for me to distinguish between "store hoisting" and "load hoisting". As far as I understood, "load hoisting" allows loading older values from a variable. However, "store hoisting" also seems to do a similar thing -  loading older values from a variable. What is "store hoisting" and how is it different from "load hoisting"?

Thank you!

**Comment by jeehoonkang** [comment]
You can think of "X hoisting" as reordering X before earlier instructions.  The load hoisting example reorders a load before an earlier store; on the other hand, the store hoisting example reorders a store before an earlier load.

**Comment by Shynar88** [comment]
Thank you so much for quick and thorough responses!!
