### ISSUE TITLE
move occurs error

### ISSUE THREAD

**Issue by anemoneflower** [kaist-cp/helpdesk#61]
Is there some way to fix
`move occurs because value has type `node::NodeBox<V>`, which does not implement the `Copy` trait` error?
I'm looking for
1. make the value to not move (way to use value as it has a copy)
or
2. way to use value after the move

thanks :)

**Comment by zoonoo** [comment]
I had encountered similar problems at first, and to my limited understanding (and I hope other people can confirm) : 

If you get "move occurs ..." error while referencing NodeBox object, chances are, that you're using the reference that is already being used as part of the Tree. See if you can use the returned values of methods like `some_nodebody.update()` or `mem::replace()`.

**Comment by anemoneflower** [comment]
Hi. I saw the use of mem::replace()
```use std::mem;

let mut v: Vec<i32> = vec![1, 2];

let old_v = mem::replace(&mut v, vec![3, 4, 5]);
assert_eq!(vec![1, 2], old_v);
assert_eq!(vec![3, 4, 5], v);
```
I think this method needs some value to replace. Can I insert original value at replace and make v and old_v same?

**Comment by anemoneflower** [comment]
Also, I couldn't find what `some_nodebody.update()` is. Can you tell me little more about it? Thanks.

**Comment by qvntm** [comment]
I think he was referring to [this](https://github.com/kaist-cp/cs492-concur/blob/212eb8c9fcc4c9be172b90f9778b9d0538b94302/art/src/node.rs#L80) function. The comment explains it well.

**Comment by anemoneflower** [comment]
Oh I see! Thanks!!
