### ISSUE TITLE
Still not clear about deletion

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#62]
From #41 question 2: Which of the trees is correct after deleting AB?:
![Screen Shot 2019-11-02 at 08 57 03](https://user-images.githubusercontent.com/38908309/68062628-d4254700-fd4e-11e9-998d-9c64f65a9893.png)
There was an answer, but I didn't understand it. Is the correct one upper or lower tree?
This seems to be easy questions, but I really spent days on understanding how the tree looks like and what happens during operations.

**Comment by zoonoo** [comment]
As I understand it : 
 - Ideally (and according to the paper) it would make sense to implement shrinking, so the tree should be as the bottom figure. 
 - However in this project, shrinking is not a requirement, so **both top and bottom figure would be correct.**

In case of my implementation, the tree stays as the top figure unless extra implementation is done.

**Comment by jeehoonkang** [comment]
I'm closing it, but feel free to reopen it for follow-up questions.
