### ISSUE TITLE
[cs492-concur][hw1-art] Do we need to consider the case not covered by the stress test cases?

### ISSUE THREAD

**Issue by zoonoo** [kaist-cp/helpdesk#67]
Currently, the random string generator makes use of `rand::distributions::Alphanumeric`, which covers only ASCII letters and numbers. 

My current (submitted) implementation covers all such cases, but it may cause a problem if the given key contains byte 255, which is some `ÿ` (U+00FF).

Would this be a problem?

**Comment by jeehoonkang** [comment]
Hmm... in my understanding of UTF-8 (https://en.wikipedia.org/wiki/UTF-8#Codepage_layout), `0xff` can never appear in a valid UTF-8 string.  But I can be wrong because I'm not an expert in encoding...

Anyway, I'll make sure byte `0xff` doesn't appear in the input strings.

**Comment by zoonoo** [comment]
Understood :)
I'm not familiar with encoding either, just wanted to know if we have to cover such cases.
