### ISSUE TITLE
Nodes as pointers

### ISSUE THREAD

**Issue by ChristPi** [kaist-cp/helpdesk#68]
I was told to use Pointers, but when using pointers how exactly do you actually get a mutable reference(of the nodes)?

**Comment by zoonoo** [comment]
I'm not sure if this will be helpful, but

note that `lookup_mut()` method in `node.rs` uses explicit type conversion from pointer to mutable reference.
https://github.com/kaist-cp/cs492-concur/blob/master/art/src/node.rs#L73

You can do the same in your unsafe block.

**Comment by ChristPi** [comment]
And I am here trying with deref_mut

**Comment by ChristPi** [comment]
wait that is only for inside a body. I want to get it in the first place

**Comment by ChristPi** [comment]
using raw pointers doesn't allow me to borrow them mutably, which I need for the Cursor. Or am I missing something?

**Comment by jeehoonkang** [comment]
@ChristPi would you please paste your code snippet?

**Comment by ChristPi** [comment]
my idea was:let (child_head, child_body) = unsafe {child.as_ref().unwrap().deref_mut().unwrap()};

**Comment by qvntm** [comment]
Just a guess but the issue is probably `let mut child: *const NodeBox` try using `*mut NodeBox` instead.

If its not working. Can you please give more details about the error? Its better to show the compilation error as it is.

**Comment by ChristPi** [comment]
I tried that one as well, but it doesn't change that child.as_ref().unwrap() will get me the cannot borrow data in a '&' reference as mutatble error

**Comment by qvntm** [comment]
Use `child.as_mut()` to get mutable reference.
