### ISSUE TITLE
What is the precise meaning of relaxed behaviors and orderings?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#7]
What is the precise meaning of relaxed behaviors and relaxed orderings?

**Comment by jeehoonkang** [comment]
- relaxed behaviors: see slide's p30
- (relaxed) ordering: it's constraining the relaxed behaviors by enforcing orders among instructions.  In particular, the "relaxed" ordering imposes no orders; the "acquire" ordering imposes order between an acquire load and later instructions; and the "release" ordering imposes order between earlier instructions and a release store.
