### ISSUE TITLE
How to move cursor.child into a new inner node

### ISSUE THREAD

**Issue by wns3645** [kaist-cp/helpdesk#71]
Hi,
I'm trying to move `self.cursor.child` into a new inner node using `update()` like below.
```rust
inner_node_body.update(child_keys[0], *self.cursor.child);
```
But I got an error on `*self.cursor.child`:
> "move occurs because `*self.cursor.child` has type `node::NodeBox<V>`, which does not implement the `Copy` trait "

How to resolve it?

**Comment by dnkim** [comment]
I think you are adjusting compressed path, that means:

Parent - Child 1 + 2
->
Parent - Child 1 - Child 2

What exactly are you trying to update? In other words, what is your `inner_node_body` and `self.cursor.child` in the figure above?

**Comment by wns3645** [comment]
I'm trying to implement L12 of pseudocode from the ART paper.
![image](https://user-images.githubusercontent.com/12604726/68105135-f373ce00-ff20-11e9-99ab-3af6182f1856.png)

For example, let's assume that we try to do (1)`art.insert("AA", 2)` and (2)art.insert("AB", 2)`.
When doing (2), I think `self.cursor.child` points the leaf node of "AA". So, we have to create a new inner node and make the `self.cursor.child` to be a child of the inner node. Is there something wrong with my thought?
((2)를 진행할 때, self.cursor.child가 처음 넣었던 'AA'에 대한 leaf node라고 생각했고 따라서 수도코드와 같이 새롭게 inner node를 만들고 self.cursor.child(for 'AA')와 새롭게 생성한 leaf node(for 'AB')를 새롭게 생성한 innder node의 children으로 넣는 것을 시도하려고 했습니다)

**Comment by qvntm** [comment]
> For example, let's assume that we try to do (1)art.insert("AA", 2) and (2)art.insert("AB", 2). When doing (2), I think self.cursor.childpoints the leaf node of "AA". So, we have to create a new inner node and make theself.cursor.child` to be a child of the inner node. 
Yes. To get the ownership of the cursor.child, you would have to delete it from the parent first.

**Comment by wns3645** [comment]
@qvntm Oh, I got it. Thanks :)
