### ISSUE TITLE
delete() vs drop() vs cleanup()

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#75]
I am confused about the purpose of drop() and its difference from delete() and cleanup().
As far as I understand, delete() is for deleting the value inside the node identified by the key, and marking that node as vacant; cleanup() is for safe deallocation of vacant nodes; However, I am not sure what is the functionality of drop() and how it is different from delete() and cleanup(). Thank you!

**Comment by jeehoonkang** [comment]
see: https://doc.rust-lang.org/std/ops/trait.Drop.html

**Comment by Shynar88** [comment]
Did I get it right: this drop() will be used/called by "safe" deallocator? Is this drop() for destroying the whole tree(dropping root)?

**Comment by jeehoonkang** [comment]
`Drop::drop()` is called for an object (allocation, variable, ...).  We model tree as an object, so when a tree is dropped, we're going to call the destructor and free all its nodes.

**Comment by Shynar88** [comment]
Will this ```drop()``` be called by ```defer_destroy()```? Or is it called directly by us?

**Comment by jeehoonkang** [comment]
`defer_destroy()` defers the destruction (including the invocation of `drop()`), which will be performed only when it is not concurrently accessed by the other threads.  You should let `defer_destroy()` to handle the actual deallucation; just implement `drop()`.
