### ISSUE TITLE
How to call ReadGuard's deref()?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#79]
I was trying to access data inside SeqLock by calling ReadGuard's deref(), but get the following error:
```no method named `deref` found for type `std::mem::ManuallyDrop<lock::seqlock::ReadGuard<'_, bst::base::NodeInner<K, V>>>` in the current scope```
Could you, please, tell how can I solve this?

**Comment by lhw941** [comment]
To extract data from `ManuallyDrop<T>`, use `into_inner()` method. To call `deref()`, just `&v` where v has type that Deref trait is implemented.

**Comment by jeehoonkang** [comment]
I'm closing it, but feel free to reopen!

**Comment by bprovot** [comment]
I don't really get it either, I also have this problem but my erro message doesn't even mention the `ManuallyDrop<T>` it says `no method named `deref` found for type `lock::seqlock::ReadGuard<'_, bst::base::NodeInner<K, V>>` in the current scope`.

Did you find a way to do what you want @Shynar88 ?

**Comment by planetarynebula** [comment]
`let a = ManuallyDrop::new(42);` 
You can dereference 42 as `*a`.
Dereferencing ReadGuard is same.
If you want to call method function of inside value, just use method like `a.f()`. 
It is possible because rust does auto-dereferencing.

**Comment by Shynar88** [comment]
@lhw941 Thank you!!
