### ISSUE TITLE
Guard parameter in find function

### ISSUE THREAD

**Issue by bprovot** [kaist-cp/helpdesk#80]
My question is simple, i have trouble understanding why do we need a guard parameter in the find function.

`    fn find(&mut self, key: &K, guard: &'g Guard) -> cmp::Ordering {
`

**Comment by jeehoonkang** [comment]
`guard` will be needed when you read pointers from memory, e.g., via `Atomic::load()` or `Atomic::compare_and_set()`.  Why it's needed is the next topic of the course: safe memory reclamation (or garbage collection).

I'm closing it, but feel free to reopen!
