### ISSUE TITLE
Return Type of the Lookup function

### ISSUE THREAD

**Issue by bprovot** [kaist-cp/helpdesk#81]
I don't really get the return type expected of the lookup function. It is written R but I really don't understand where I should get that value from.

**Comment by Shynar88** [comment]
I think answer can be inferred from the following line from test_bst: ```assert_eq!(bst.lookup(&String::from("bb")), Some(&37));```  
So, R is probablly of type Option. And value can be taken from NodeInner.
Hope this helps!

**Comment by bprovot** [comment]
It makes sense, thanks.
