### ISSUE TITLE
CleanUp function coverage

### ISSUE THREAD

**Issue by bprovot** [kaist-cp/helpdesk#83]
Does the cleanup function of the cursor has do a full cleanup of the tree or just check if the current node is "cleanup-able" ?

**Comment by jeehoonkang** [comment]
The latter: cleanup iteratively until the current node is no longer cleanup-able.

**Comment by jeehoonkang** [comment]
I've updated the skeleton code's comment.  I'm closing it, but feel free to reopen it!
