### ISSUE TITLE
get_mut / read difference

### ISSUE THREAD

**Issue by bprovot** [kaist-cp/helpdesk#84]
I don't really get the difference between the `get_mut()` and `read` functions that are available when working on the ReadLock to access the inner node. For example in the `fn cleanup` I want to get the inner value of the node I am working on and I really don't know what to chose.

**Comment by jeehoonkang** [comment]
If you're calling `AtomicRW::atomic_write()` or `AtomicRW::atomic_swap()`, then you should have acquired a `WriteGaurd`.  More generally, if you're actualy writing to the inner value via interior mutability, you should probably have a `WriteGuard`.  In other cases, `ReadGuard` is enough.

**Comment by Shynar88** [comment]
Do you mean that for getting inner value of the node we should only use ```read``` and not ```get_mut()```?

**Comment by jeehoonkang** [comment]
@Shynar88 @bprovot I believe this comment helps you for this question: https://github.com/kaist-cp/cs492-concur/issues/17#issuecomment-558465665

**Comment by bprovot** [comment]
I don't really understand

**Comment by jeehoonkang** [comment]
In general, if you're reading the value and child pointers, then you can just use read guard's `deref()` as far as the reads are validated.  If you're writing to them, you should use write guards.

**Comment by bprovot** [comment]
Thank you, I figured that 15 minutes ago !! Thanks a lot
