### ISSUE TITLE
Using upgrade functions in homework

### ISSUE THREAD

**Issue by lumiknit** [kaist-cp/helpdesk#86]
Can we use `RawSeqLock.upgrade` and `ReadGuard.Upgrade` in homework 2?

**Comment by efenniht** [comment]
I made that PR (kaist-cp/cs492-concur#27) for my homework :) So, why not?

**Comment by lumiknit** [comment]
I got some errors that `upgrade` function was not found, but I just now noticed that they occur because cached dependencies was not updated... 
Thanks.
