### ISSUE TITLE
How to write `data` via `WriteGuard`?

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/helpdesk#87]
`seqlock.rs`'s `WriteGuard` has only `deref` which returns a refernence of its data.
I think it should also have a way to return a mutable reference of its data. (such as `deref_mut`)
Or, is there any way to write its data?

**Comment by Pusnow** [comment]
I've found `AtomicRW` trait for the purpose.

However, I'm still curious why there is no `deref_ref`.

**Comment by jeehoonkang** [comment]
`deref_mut` will be unsafe because even though you've acquired a `WriteGuard`, a concurrent `ReadGuard` may be performing reads at the same time.  `deref_mut` incorrectly assumes there're no concurrent readers/writers.

**Comment by Pusnow** [comment]
Ok.
