### ISSUE TITLE
Why casualty test case 16 is wrong?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#9]
Causality test case 16

Initially, x = 0

Thread 1:
r1 = x
x = 1

Thread 2:
r2 = x 
x = 2

Behavior in question: r1 == 2; r2 == 1

Decision: Allowed.
***************
It is written on the lecture slides that case 16 is wrong. However, we can do load-store reordering in Thread 2, by doing this, r1 == 2; r2 == 1 will be allowed. 

Execution:
Thread 2:
x = 2
Thread 1:
r1 = x
x = 1
Thread 2:
r2 = x 

Am I missing something?
Thank you!

**Comment by Shynar88** [comment]
Similar question concerning case #19:
***********
Causality test case 19

Initially,  x = y = 0

Thread 1:
join thread 3
r1 = x
y = r1

Thread 2:
r2 = y
x = r2

Thread 3:
r3 = x
if (r3 != 42)
  x = 42

Behavior in question: r1 == r2 == r3 == 42

Decision: Allowed. This is the same as test case 17, except that thread 1 has been
  split into two threads.
**********

Why casualty test case 19 is wrong? I have an assumption that if "joining thread" is allowed to be reordered with later instructions, then case #19 becomes the same as case #17, where behaviour is Allowed. However, if "joining thread" is never reordered with later instructions, then behaviour is Disallowed. So, is my assumption("joining thread" is never reordered) right reason why behaviour is Disallowed?

Thank you!

**Comment by jeehoonkang** [comment]
Again, you're reordering instructions beyond what's allowed.  For example, in test case 16, r1=x and x=1 cannot be reordered because they're accessing the same location.

**Comment by Shynar88** [comment]
What about joining the thread? Is it also not allowed to reorder the moment of joining the thread?

**Comment by jeehoonkang** [comment]
FWIW, it is safe to assume a thread exit/join pair is synchronizing like a pair of release/acquire.  Yes, you cannot reorder a thread join with later instructions.

**Comment by Shynar88** [comment]
Concerning case 16. I tried using the promising semantics, but got "Allowed" result. Where did I go wrong in my reasoning?
1) Initial views: 
![Screen Shot 2019-10-14 at 01 17 57](https://user-images.githubusercontent.com/38908309/66718590-6efdc600-ee20-11e9-8673-38aa67f1b7c6.png)
2) Thread 1 makes the promise X = 1, Thread 2 makes the promise X = 2. Both are certified, as can those promises can be fulfilled when their threads are executed in isolation.
![Screen Shot 2019-10-14 at 01 20 25](https://user-images.githubusercontent.com/38908309/66718615-c734c800-ee20-11e9-8de7-f3f455140ffc.png)
3) After thread 1 is executed, r1 = 2 and promise X = 1 is re-certified and fulfilled.
![Screen Shot 2019-10-14 at 01 22 49](https://user-images.githubusercontent.com/38908309/66718645-1da20680-ee21-11e9-93ce-5347abcf6d27.png)
4) After thread 2 is executed, r2 = 1 and promise X = 2 is re-certified and fulfilled.
![Screen Shot 2019-10-14 at 01 23 46](https://user-images.githubusercontent.com/38908309/66718664-3f02f280-ee21-11e9-98fe-e6eb528adca9.png)

**Comment by jeehoonkang** [comment]
3. is wrong.  t1's view is pointing to X=2, so it cannot fulfill an earlier message X=1.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have followup questions.
