### ISSUE TITLE
What does the push function do with current?

### ISSUE THREAD

**Issue by snyokang** [kaist-cp/helpdesk#90]
There are two variables named 'current', I got confused.

Does it push 'current' to 'self.current'?

**Comment by AnuarTB** [comment]
@jeehoonkang

**Comment by jeehoonkang** [comment]
https://github.com/kaist-cp/cs492-concur/blob/master/homework/src/bst/mod.rs#L31

`current` should be the new `self.current`.  The original `self.current` will go to `ancestors`.

**Comment by jeehoonkang** [comment]
Closing it, but feel free to reopen it.
