### ISSUE TITLE
Implementation of Retry

### ISSUE THREAD

**Issue by planetarynebula** [kaist-cp/helpdesk#92]
I am confused at implementing *Retry*.
In the paper Figure 5, find function is described. It checks node version after reading values in node. If the node is stale(the version is changed), it returns *Retry*.
I think that checking node version is implemented with `ReadGuard`. When I found `ReadGuard` is not validate, we need to restart and do *Retry*.

However, I think there are several ways to implement *Retry* and I don't know what to choose.

1. Retry search from the root. It is accurate but slow. 
2. Just restart ReadGuard and retry from the current node. I think it has some problem when concurrent writing occurrs.
3. Retry search from the parent node of the current one. If it is also stale, go parent until it is not stale. I understood that the paper uses this method. 

~~What should I use?~~
I concluded that we should use 3rd method according to the paper.

**Comment by planetarynebula** [comment]
Oh, I found the [comment](https://github.com/kaist-cp/cs492-concur/issues/17#issuecomment-558465665) that tells read value should be protected by `WriteGuard`, not `ReadGuard`.
Then I think we don't need to do *Retry*. Did I understand right?

**Comment by mjy0503** [comment]
I understand that comment is only applied to read value using f: FnOnce in `ConcurrentMap::lookup()`.
In other cases, I think we should read value with `ReadGuard`.

**Comment by planetarynebula** [comment]
I read the paper carefully and I concluded that it is enough to implement according to the code in the paper.

**Comment by tomtomjhj** [comment]
@planetarynebula but how do you know if a node is stale or not?

**Comment by planetarynebula** [comment]
I think, we should use (1) validate check function in `readGuard` and (2) `n.version == Unlinked` check implemented by tag in `crossbeam_epoch::Shared`.
But, it is just my opinion. So, I need some confirm from professor @jeehoonkang

**Comment by planetarynebula** [comment]
I think it should be another issue. I made a new [issue](https://github.com/kaist-cp/helpdesk/issues/105#issue-530189835)
