### ISSUE TITLE
shouldn't cursor.ancestors also keep the ReadGuards?

### ISSUE THREAD

**Issue by tomtomjhj** [kaist-cp/helpdesk#94]
1. `long chV = child.version` and `node.version ^ nodeV` are equivalent to acquiring `ReadGuard` and its validation respectively.
    1. However every `((node.version^nodeV) & IgnoreGrow) != 0)` check is meaningless because no rebalancing implies no shrinking.
2. `cursor.push()` is equivalent to recursive call of `attempt{Get,Put,Remove}`
3. `cursor.pop()` is equivalent to `return Retry` in `attempt{Get,Put,Remove}` (this doesn't include returns from helper functions `attempt{Insert,Update,RmNode}`)
4. Since each `attempt{Get,Put,Remove}` has `node, dir, nodeV` parameters, `cursor.ancestors` should also contain the corresponding `ReadGuard`s along with the node ptr and the direction. However, it doesn't.
5. 1.i and 4 imply that `cursor.pop()` is not needed and cannot be implemented.

Is there any wrong assumption or wrong conclusion?

**Comment by tomtomjhj** [comment]
`Retry` is not necessary if rebalancing is skipped.

**Comment by dnkim** [comment]
Do you mean we can just `restart` `ReadGuard` and `validate` it?

**Comment by tomtomjhj** [comment]
@dnkim I have no idea.

**Comment by tomtomjhj** [comment]
My conclusion is:
* 1,2: correct
* 4: by 1.i, they are not needed
* 3,5: `pop` is for `cleanup`

**Comment by dnkim** [comment]
But `(node.version^nodeV) & IgnoreGrow) != 0` also checks if the node is unlinked, doesn,t it?

**Comment by tomtomjhj** [comment]
@dnkim hmm i think you're right.
