### ISSUE TITLE
Key exists in the tree, value is None. Should we return Err or update the value to new one?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#96]
In #78, q2 is still unclear for me.
Key exists in the tree, value is None. Should we return Err or update the None to new value?

**Comment by qvntm** [comment]
From [here](https://github.com/kaist-cp/cs492-concur/blob/794ec95d9fc25f634a30b54d36c9c5f142667fa4/homework/src/bst/base.rs#L35)
>Value on the node. `None` means it's vacant

Read the comments carefully.

**Comment by Shynar88** [comment]
@qvntm , I know about this comment. It is not clear for me during the insertion, if Key exists in the tree, value is None. Should we return Err or update the None to new value?

**Comment by qvntm** [comment]
>Returns `Err(value)` for the given `value` if `key` is already occupied.
Vacant means its not occupied so no, you shouldn't return `Err`.

**Comment by Shynar88** [comment]
@qvntm , Thank you!!
