### ISSUE TITLE
How to configure LLDB?

### ISSUE THREAD

**Issue by Shynar88** [kaist-cp/helpdesk#97]
My LLDB worked fine with ART.
However, it doesn't work now. The launch.json wasn't automatically configured and I filled it manually. However, when I run debugger it crashes with ```Cargo invocation has failed: Error: could not launch cargo: Error: spawn cargo ENOENT```.

My launch.json looks like this:
![Screen Shot 2019-11-27 at 17 22 32](https://user-images.githubusercontent.com/38908309/69706428-09993680-113b-11ea-86a4-c7aad0dfa965.png)

Could you, please, tell how should I change the launch.json? Issue #26 didn't help

**Comment by jeehoonkang** [comment]
- Please paste code as `code`, not image.
- It seems VSCode cannot find your `cargo`...  It's strange it could for the development for homework 1.  Can you figure out what's different from HW1?

**Comment by Shynar88** [comment]
The problem was solved by opening only homework directory in VSCode. In this way LLDB can autoconfigure launch.json. Previously, my VSCode had entire cs492-concur directory opened.
