### ISSUE TITLE
About Calling upgrade Method

### ISSUE THREAD

**Issue by dnkim** [kaist-cp/helpdesk#98]
Is there any way to call `ReadGuard::upgrade` for the `value` of `cursor.guard` where `cursor` has type `&mut Cursor`? Or can I implement the whole code without any such cases?

**Comment by dnkim** [comment]
I used `mem::replace`.

**Comment by planetarynebula** [comment]
How can you use `mem::replace`? I want to use `upgrade`, too. But, I am confused what to give into `replace` function as an argument value.

**Comment by dnkim** [comment]
I gave `&mut cursor.guard` as `src` of `mem::replace` and called `upgrade` on the returned value.

**Comment by planetarynebula** [comment]
Actually, I have no idea about `src`. I want to give `null` value. But, I don't know such way. If I am traveling tree, then I may possible to give child's guard as `src`. But, it is not always possible.

**Comment by planetarynebula** [comment]
Oh, I found ManuallyDrop has `take` unsafe function. I think it is good to use since `ReadGuard` is never dropped before its `finish` function is called.

**Comment by bprovot** [comment]
@planetarynebula Don't you have an error when calling into_inner on the guard ?
