### ISSUE TITLE
Removing Routing Node

### ISSUE THREAD

**Issue by planetarynebula** [kaist-cp/helpdesk#99]
In the paper, routing nodes are removed in rebalancing function. In HW#2, however, no rebalancing function exists. So I wonder if it is necessary to delete a routing node when its child is removed.

**Comment by jeehoonkang** [comment]
`cleanup()`'s purpose is removing a node that is (1) vacant, i.e. the value is `None`, and (2) having at most one child, i.e. either left or right child is null.  Also you should recursively traverse up the tree and cleanup such nodes.

**Comment by mjy0503** [comment]
For clarification,  If `self.current` is cleanup-able, I physically remove `self.current`.
And then call `cleanup()` recursively with parent of previous `self.current`.
Is it right?

And When we call `cleanup()` function?

**Comment by mjy0503** [comment]
@jeehoonkang

**Comment by jeehoonkang** [comment]
@mjy0503 yeah, it's right.  Call `cleanup()` in `remove()` because the node is vacant and thus cleanup-able.
